### ISSUE TITLE
Magento Quote ID is being used as Razorpay Order ID instead of Magento Order ID

### ISSUE THREAD

**Issue by ghost** [razorpay/razorpay-magento#109]
In Razorpay transactions the field displayed as Order ID is not same as Magento Order ID. I checked the tables and found that Quote ID is being used to display Order ID. This should be changed so that we have one to one mapping with Magento Order ID and Razorpay Order ID for reconciliation.

**Comment by desire-desire** [comment]
Hi  Razorpay

We are facing the same issue.  Definitely we need a fix for this

**Comment by ramth05** [comment]
Already supported in latest releases.
