### ISSUE TITLE
Unable to create orders from Magento 2 Dashboard

### ISSUE THREAD

**Issue by devuberoi** [razorpay/razorpay-magento#115]
While creating orders from Magento 2's Admin dashboard and selecting razorpay as payment method, it gives error :

**Razorpay Error: Either razorpay_order_id or razorpay_subscription_id must be present**

There is no field to input this value in the order creation form. Please help.

**Comment by Mayur-Wadpalliwar** [comment]
Hello @devuberoi,

We do not support this at the moment.

**Comment by ecohivetech** [comment]
> While creating orders from Magento 2's Admin dashboard and selecting razorpay as payment method, it gives error :
> 
> **Razorpay Error: Either razorpay_order_id or razorpay_subscription_id must be present**
> 
> There is no field to input this value in the order creation form. Please help.

did you find any solution for this?

**Comment by ramth05** [comment]
Currently not supported by Razorpay.
