### ISSUE TITLE
Checkout Address Update Not working for Magento 2 CE v2.1.3

### ISSUE THREAD

**Issue by brijtz** [razorpay/razorpay-magento#116]
The extension does not work with Magento 2.1.x ( we are using 2.1.2). We are getting an error as an attached file when we try to update an address while checkout. (Product type: Virtual/Downloadable)
![updateaddress-magedelight-razorpay](https://user-images.githubusercontent.com/22252973/43060059-e34f68de-8e6c-11e8-8917-1c399c51fd40.png)

**Comment by jpeevi** [comment]
Hello,

We've tested the same from our end, despite the console error, the payment flow was not hindered. 
Can you kindly confirm on the same?

**Comment by Aniket10Nov** [comment]
Yes, Payment method is working. But if you assign different methods to the different country and try to change your billing address then it will not change according to the billing address. 
Expected Result:- Payment methods should be changed according to change different change of billing address.
Actual Result:- Payment Method not changed as we changed billing address. If we disable Razor pay from backend then it's working properly.

**Comment by ramth05** [comment]
Already fixed in latest releases.
