### ISSUE TITLE
Pop Up Issue 

### ISSUE THREAD

**Issue by nilkanthray** [razorpay/razorpay-magento#117]
<img width="829" alt="screen shot 2018-07-23 at 2 25 07 pm" src="https://user-images.githubusercontent.com/11885465/43074542-4da18c34-8e9b-11e8-8fbd-527bbfe406a2.png">

Have installed Magento Version 1.9.3.6 but somehow the pop is not coming up for the payment process

Please help

**Comment by Mayur-Wadpalliwar** [comment]
@nilkanthray We have tested our plugin against the same Magento version you are using and it is working fine for us.

Could you please try re-installing the plugin?

Also, please share the website details so that we could have a look?

**Comment by nilkanthray** [comment]
Hello Mayur,

The Website is https://www.nutracart.com/ , Could you please recheck once

**Comment by jpeevi** [comment]
@nilkanthray  we tested your checkout, there's something wrong with how the payment method form gets rendered on your frontend, firstly a form_key is missing the second issue is that  Magento's **savePayment** is returning null on submission. This could be associated with your theme or Magento installation itself. 

![mg_render](https://user-images.githubusercontent.com/5638276/43078729-ecb1d51a-8ea8-11e8-9375-b6684c6667e4.png)

**Comment by harman28** [comment]
Closing due to lack of response. Please do not hesitate to re-open if you are (or anyone else is) still facing this issue.
