### ISSUE TITLE
Razorpay payment option not displayed

### ISSUE THREAD

**Issue by NamithaPishe** [razorpay/razorpay-magento#118]
Hi,
I just installed the code from the zip "razorpay-magento-1.1.19" on my Magento 1.9.2.4 version. On click of submit on the checkout page, I am directed to a page which says "Please wait, do not refresh your page" and nothing happens. Is there any configuration I am missing. Below is a screenshot of the page I am directed to on submitting the order-

![capture](https://user-images.githubusercontent.com/42470206/44296831-87895380-a2e3-11e8-822c-b6301377fb40.JPG)

Your help is greatly appreciated.

Regards,
Namitha.

**Comment by ramth05** [comment]
@NamithaPishe, please try to use latest release from here in case of Magento 1.x 
https://github.com/razorpay/razorpay-magento-v1/releases/tag/1.2.0
Magento 2.x 
https://github.com/razorpay/razorpay-magento/releases/tag/2.9.2
