### ISSUE TITLE
Error on checkout page. 

### ISSUE THREAD

**Issue by Aniket10Nov** [razorpay/razorpay-magento#119]
Magento version 2.2.5.
On checkout page getting an error of Uncaught TypeError: this.elems is not a function on collection.js

Because of the error payment method is not change according to the selected billing address.

**Comment by jpeevi** [comment]
Hello ,

Can you refer to this thread - https://github.com/razorpay/razorpay-magento/issues/110

**Comment by harman28** [comment]
Closing as duplicate of #110
