### ISSUE TITLE
Razorpay Error: Curl Error during place order magento 1.9

### ISSUE THREAD

**Issue by allinvinod** [razorpay/razorpay-magento#122]
Hi All,

I had integrate razorpay payment gateway in magento 1.9

When I click on please order button it is redirect to failure url: https://example.com/staging/index.php/checkout/onepage/failure/

And showing an curl error: 
![curl error1](https://user-images.githubusercontent.com/22171945/48826018-38920500-ed8f-11e8-8ccb-e691cac7f1d8.png)

Can anyone suggest how can I fix the issue?

**Comment by ramth05** [comment]
@allinvinod can you please try to install latest release from here in case of Magento 1.x 
https://github.com/razorpay/razorpay-magento-v1/releases/tag/1.2.0
Magento 2.x
https://github.com/razorpay/razorpay-magento/releases/tag/2.9.2
