### ISSUE TITLE
i get 400 bad request

### ISSUE THREAD

**Issue by refaelgold** [razorpay/razorpay-magento#13]
GET http://pilo.php7.stage.agent.co.il/razorpay/payment/order?_=1465896779631 400 (Bad Request)

any idea how to fix it?

**Comment by captn3m0** [comment]
Your site is hidden behind a password, it seems. If the bad request error is propogating from Razorpay, we will be sending a reason along with the response in the body.

**Comment by refaelgold** [comment]
U: stage
P: Boof1j 

do you have any test detail to put on admin for checking your module?

**Comment by captn3m0** [comment]
You are getting a `cURL error 77:`. Probable cause is that you do not have CACertificates installed properly on your system.  You can see https://stackoverflow.com/questions/17064601/curl-not-working-error-77-for-ssl-connections-on-centos-for-non-root-users for more details.

If you are running ubuntu/debian you can just do `sudo apt-get install ca-certificates`

**Comment by captn3m0** [comment]
You will need to set your Key Id and Key Secret which you can obtain by signing up at dashboard.razorpay.com if you haven't already

**Comment by refaelgold** [comment]
i allready put - i must install CACertificates ?

**Comment by refaelgold** [comment]
Do you have any dummy data for testing?

**Comment by refaelgold** [comment]
In addiation - i got 
collection.js:237 Uncaught TypeError: this.elems is not a function

**Comment by captn3m0** [comment]
That is an error on the magento javascript, and we can't do anything about that.

**Comment by refaelgold** [comment]
Its only happend when i activate your module.

now youe module is disabled and the error is gone...

**Comment by captn3m0** [comment]
Please send a mail to `integrations@razorpay.com` with your PHP and magento version, and we'll take it from there.

**Comment by refaelgold** [comment]
I send my email and waiting for response. 

i leave this issue open for other users who maybe have the same issue

i use php 7.0.6 and M2 version 2.0.7

**Comment by mayankamencherla** [comment]
Solving on email.

**Comment by nareshphp1** [comment]
I am getting error "There was an error capturing the transaction. BAD_REQUEST_ERROR: The requested URL was not found on the server."  on checkout page when I select payment method Razorpay while placing order in magento site/store.
![checkout life - google chrome 2018-05-01 12 09 39](https://user-images.githubusercontent.com/14833512/39463969-9ce88440-4d38-11e8-961a-1e4c555143f3.png)

**Comment by Aniket10Nov** [comment]
Same error i am getting on checkout.
In addiation - i got
collection.js:237 Uncaught TypeError: this.elems is not a function.
Any solution for this?

**Comment by chitra-bahadur** [comment]
@captn3m0 i am getting bad_request error with message="unauthorized", i am using below url in android with retrofit
i am using test mode. its working in postman.
url: 'https://<YOUR_KEY_ID>:<YOUR_KEY_SECRET>@api.razorpay.com/v1/payments/pay_29QQoUBi66xm2f/capture', 
 form: {    amount: 5000  },

**Comment by captn3m0** [comment]
Please don't use your secret key in your Android app. Private auth is not meant to be used from public applications.

**Comment by chitra-bahadur** [comment]
@captn3m0 can you share any link or document how to properly integrate in android app for capturing the payments.

**Comment by Mayur-Wadpalliwar** [comment]
Steps:
1. Create order at Razorpay from your backend server using the API: https://razorpay.com/docs/api/orders/#create-an-order with payment_capture: 1
2. You would get **razorpay_order_id** as part of the response 
3. Pass **razorpay_order_id** to android and invoke checkout along with other options
4. Implement **PaymentResultWithDataListener** to get razorpay_order_id and razorpay_siganture in the response as suggested here: https://razorpay.com/docs/payment-gateway/orders/migration/#checkout-on-android
5. Pass these 3 values to your backend server for signature verification. (https://razorpay.com/docs/payment-gateway/orders/integration/#step-4-payment-verification)
6. Process the transaction if signature verification is successful

**Comment by chitra-bahadur** [comment]
@captn3m0 
getting below error API_SECRET not working which i have provided
Could not resolve host: KEY_SECRET
{"error":{"code":"BAD_REQUEST_ERROR","description":"The api secret provided is invalid"}

**Comment by Vishal-Magento** [comment]
Hello 
From few days razorpay is not working for customers... facing issue: "cURL error 6: Could not resolve host: api.razorpay.com"
before it was working fine Can you please help... Thanks In Advance.
Magento v: 2.4.2.

**Comment by laxus456** [comment]
Hi,
I have an error which said that "Amount exceeds maximum amount allowed." even though i only have 2 usd as input.
I also check my console log which resulted to:

![image](https://user-images.githubusercontent.com/60313901/174292151-9db7bf91-bc61-4daf-929b-33f6fb27930c.png)

i already entered the key and secret in my controller to test it

**Comment by muhammed-ijlan** [comment]
Hi,
I have an error which said that "Amount exceeds maximum amount allowed." even though i only have 500 INR as input.
how to fix this.?

**Comment by hypothesistribetechnology** [comment]
getting same erro in _wrapXHR function
