### ISSUE TITLE
 BAD_REQUEST_ERROR:The requested URL was not found on the server

### ISSUE THREAD

**Issue by sharon-tst** [razorpay/razorpay-magento#138]
I am try to create a plan in razor-pay using java but i get an error BAD_REQUEST_ERROR:The requested URL was not found on the server. Why  this happen ? Any solution for this ?

**Comment by harman28** [comment]
It is likely that you do not have the subscriptions feature enabled on your account, and thus do not have access to the API endpoints. You can request access from the Subscriptions section of your Razorpay dashboard.
You can also use the [razorpay-java](https://github.com/razorpay/razorpay-java) repo to report these issues, or directly use [Razorpay Support](https://razorpay.com/support/)
