### ISSUE TITLE
How to add redirection_url

### ISSUE THREAD

**Issue by sharon-tst** [razorpay/razorpay-magento#139]
I can create a short_url using Invoice creation in razor-pay using java code . After payment success how can i redirect my site ? How can i add redirection_url ? Any solution for this ?

**Comment by harman28** [comment]
The short URL is generally not used for redirection, but exists for sharing with the customer. You can do so yourself, or you can use the [sms_notify/email_notify attributes](https://razorpay.com/docs/invoices/api/#create-an-invoice) while creating the invoice, in which case Razorpay will send the notification.

If you find yourself needing to accept payment from the customer directly, without any notification, you  can pass invoice_id as one of the [parameters to checkout.js](https://razorpay.com/docs/payment-gateway/integrations-guide/checkout/standard/#checkout-form).
