### ISSUE TITLE
not supported on Magento 2.1.0-rc3

### ISSUE THREAD

**Issue by refaelgold** [razorpay/razorpay-magento#14]
this log: 

   - Installation request for razorpay/magento ^2.0 -> satisfiable by razorpay/magento[2.0.2].
    - Conclusion: remove magento/framework 100.1.0-rc3
    - Conclusion: don't install magento/framework 100.1.0-rc3
    - razorpay/magento 2.0.2 requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - Can only install one of: magento/framework[100.1.0-rc3, 100.0.2].
    - Can only install one of: magento/framework[100.1.0-rc3, 100.0.3].
    - Can only install one of: magento/framework[100.1.0-rc3, 100.0.4].
    - Can only install one of: magento/framework[100.1.0-rc3, 100.0.5].
    - Can only install one of: magento/framework[100.1.0-rc3, 100.0.6].
    - Can only install one of: magento/framework[100.1.0-rc3, 100.0.7].
    - Can only install one of: magento/framework[100.1.0-rc3, 100.0.8].
    - Can only install one of: magento/framework[100.1.0-rc3, 100.0.9].
    - Installation request for magento/framework (locked at 100.1.0-rc3) -> satisfiable by magento/framework[100.1.0-rc3].

**Comment by arvind07** [comment]
Hi,
I am trying to upgrade to Magento 2.1.0 but I am getting the above error.
Is there any update on how to fix it?

Thanks

**Comment by andimov** [comment]
@refaelgold 
please, provide description according to the template.

**Comment by arvind07** [comment]
@andimov Just upgrade your existing Magento 2 installation to latest 2.1.0 through command line.
You will face the above error.

**Comment by arvind07** [comment]
Any update for Magento 2.1.0?

**Comment by 73sl4** [comment]
@arvind07 We have updated our magento-2.x for Magento 2.1 support.
Can you please try installing the plugin now.

**Comment by 73sl4** [comment]
Fixed in #20
