### ISSUE TITLE
No data in $request['paymentMethod']['additional_data']

### ISSUE THREAD

**Issue by surmatech** [razorpay/razorpay-magento#142]
Razorpay Error: Notice: Undefined index: rzp_payment_id in /var/www/html/vendor/razorpay/magento/Model/PaymentMethod.php on line 205."

and 

Razorpay Error: Notice: Undefined index: rzp_signature in ...

I am using a popular OnePageCheckout plugin and Magento 2.3.1

**Comment by surmatech** [comment]
{"message":"Razorpay Error: Notice: Undefined index: rzp_payment_id in \/var\/www\/html\/vendor\/razorpay\/magento\/Model\/PaymentMethod.php on line 205.","trace":"#0 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('PhcnRkh1lWvvYJ3...', 'admin@kjskdj.co...', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#1 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->___callParent('savePaymentInfo...', Array)\n#2 \/var\/www\/html\/app\/code\/Aheadworks\/OneStepCheckout\/Model\/Plugin\/GuestNewsletterSubscriber.php(51): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}('PhcnRkh1lWvvYJ3...', 'admin@kjskdj.co...', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#3 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Aheadworks\\OneStepCheckout\\Model\\Plugin\\GuestNewsletterSubscriber->aroundSavePaymentInformationAndPlaceOrder(Object(Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor), Object(Closure), 'PhcnRkh1lWvvYJ3...', 'admin@kjskdj.co...', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#4 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}('PhcnRkh1lWvvYJ3...', 'admin@kjskdj.co...', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#5 \/var\/www\/html\/generated\/code\/Magento\/Checkout\/Model\/GuestPaymentInformationManagement\/Interceptor.php(26): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)\n#6 [internal function]: Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder('PhcnRkh1lWvvYJ3...', 'admin@kjskdj.co...', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#7 \/var\/www\/html\/vendor\/magento\/module-webapi\/Controller\/Rest\/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#8 \/var\/www\/html\/vendor\/magento\/module-webapi\/Controller\/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#9 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#11 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/var\/www\/html\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#13 \/var\/www\/html\/vendor\/magento\/framework\/App\/Http.php(136): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#14 \/var\/www\/html\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#15 \/var\/www\/html\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#16 \/var\/www\/html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#17 {main}"}

**Comment by ramth05** [comment]
This plugin supports all the basic theme based plugins. Please try latest one.

**Comment by Dann8439** [comment]
Hi team i am facing this type of issue can you please help me out for this

Razorpay Error: Notice: Undefined variable: rzp_order_id in 
/app/code/Razorpay/Magento/Model/PaymentMethod.php on line 371.",
