### ISSUE TITLE
Magento 2.6 Can't Accept Checkout Agreements Before Routing to razorpay

### ISSUE THREAD

**Issue by pavithra-expedux** [razorpay/razorpay-magento#143]
When i click pay with razorpay button it should validate terms and condition checked. if it is checked then only it should route to razorpay. But it checking validation after done payment   ![image](https://user-images.githubusercontent.com/44948028/59340794-51123e80-8d24-11e9-8a50-1cf19d24d265.png) .
 For other payment method working good 
![image](https://user-images.githubusercontent.com/44948028/59341414-6cca1480-8d25-11e9-84b3-5c77b4516a0c.png)

**Comment by ramth05** [comment]
Already fixed in latest releases.
