### ISSUE TITLE
Rozorpay Magento2 cart & Checkout page not working after installation

### ISSUE THREAD

**Issue by vk44295** [razorpay/razorpay-magento#146]
Hi, 
I have a website http://styleatwork.in/demo/ and i want to use rozorpay payment gateway for my website. when i installed the the module of rozorpay i will stuck the cart & checkout page. my website based on magento 2.2.6 Can any one check the issue.

Error Ref: 
(https://user-images.githubusercontent.com/26023504/60503526-8daad780-9cdd-11e9-9807-38b3d0aeaf28.png)

**Comment by harman28** [comment]
@vk44295 The error occurs if your setup doesn't have [razorpay-php](https://github.com/razorpay/razorpay-php/) classes in it.

If you're using composer for installing this plugin, dependencies are handled and this shouldn't occur. How did you install `razorpay-magento`?

**Comment by vk44295** [comment]
@harman28  I have installed manually as they provide the link to download and install the same.

**Comment by harman28** [comment]
@vk44295, In that case, you'll need to download the dependencies as well. Grab the [latest release of razorpay-php](https://github.com/razorpay/razorpay-php/releases) and follow the installation instructions in the [README](https://github.com/razorpay/razorpay-php/blob/master/README.md), and it should work.

> as they provide the link to download

Could you share this link, i.e. let me know where you downloaded this from? Want to check if there's some incorrect instruction somewhere.

**Comment by vk44295** [comment]
@harman28 Sure I have received below email:

Hi Vikash,

Greetings from Razorpay.
​
Could you please uninstall the existing Magento file and try to install the latest version by using the steps given in the
following link: **https://razorpay.com/docs/ecommerce-plugins/magento/2.x/**
Let us know if you are still facing the issue.

Here to help :)
Giridhar M

The ticket reference for your request is #571086.

**Comment by harman28** [comment]
@vk44295 Thanks for this. That doc page doesn't make it clear that dependencies need to be addressed if one isn't using composer. I'll get it updated.

**Comment by vk44295** [comment]
@harman28  Can you please check if i will provide website credentials.  Currently i have uninstalled razorpay module.

**Comment by harman28** [comment]
@vk44295 If you can share error details here, I'll be able to help you out. 

For any additional integration support, you can report it via our official [support portal](https://razorpay.com/support/) and get assistance.

**Comment by vk44295** [comment]
@harman28  Ok thanks. can you please guide us the steps to install razorpay for magento 2 version.

**Comment by harman28** [comment]
@vk44295 The steps on [this page](https://razorpay.com/docs/ecommerce-plugins/magento/2.x/) are correct. I'd also recommend using composer instead of downloading the zip file manually.

**Comment by vk44295** [comment]
@harman28 I am unable to install using composer getting error please check it.
http://prntscr.com/oauu4w

**Comment by harman28** [comment]
@vk44295 You are pasting the two commands in a single line. Please paste them separately, as they are two separate commands.

**Comment by vk44295** [comment]
@harman28  Now i have used separately and getting following error.

http://prntscr.com/oav66i

**Comment by vk44295** [comment]
@harman28  My php version: 
http://prntscr.com/oav7c7

**Comment by harman28** [comment]
@vk44295 Can you share your composer.json file?

**Comment by vk44295** [comment]
@harman28 Sure sir

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.2.6",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.2.6",
        "composer/composer": "@alpha"
    },
    "require-dev": {
        "phpunit/phpunit": "~6.2.0",
        "squizlabs/php_codesniffer": "3.2.2",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.5.2",
        "friendsofphp/php-cs-fixer": "~2.2.1",
        "lusitanian/oauth": "~0.8.10",
        "sebastian/phpcpd": "2.0.4"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}

**Comment by ramth05** [comment]
@vk44295  Can you please provide us output of  `composer -vvv about`

**Comment by vk44295** [comment]
@harman28  Yes sure

http://prntscr.com/oax7rt

**Comment by ramth05** [comment]
@vk44295 Can you please try to upgrade your composer setup to use your latest PHP 7.x installation.
This looks like your composer still using PHP 5.6 .

**Comment by vk44295** [comment]
@harman28 How can i upgrade i have no idea about that.

**Comment by harman28** [comment]
@vk44295  We'll be able to help if you're facing any issues with the razorpay-magento setup. For composer upgrade, could you try seeing if you're able to update it yourself? Any issues you face will be common and fixes easy to find.

If you do still need help, you can report it via our official [support portal](https://razorpay.com/support/) and get assistance. I'd advise you to do this, since it would allow you to share your contact number as well, and we'll be able to provide more involved support over a call.

**Comment by ramshankar5july** [comment]
Hi Razorpay Team,

I have installed magento ver 2.3.0 on website https://www.prakratee.com and on this website when I installed extension version 2.7.0. cart page and checkout page is showing error. Kindly see below
"
This page isn’t working 
www.prakratee.com is currently unable to handle this request.
HTTP ERROR 500
"
Please fix this issue and my ticket ID is - 
Ticket ID - 615736 [Merchant] Technical Assistance

**Comment by ramth05** [comment]
@ramshankar5july , can you please try latest release from here https://github.com/razorpay/razorpay-magento/releases/tag/2.9.2
