### ISSUE TITLE
RAZ PAY INSTALL PROBLEM

### ISSUE THREAD

**Issue by sivadasbca** [razorpay/razorpay-magento#149]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install composer/composer 1.8.6
    - Conclusion: don't install composer/composer 1.8.5
    - Conclusion: don't install composer/composer 1.8.4
    - Conclusion: don't install composer/composer 1.8.3
    - Conclusion: don't install composer/composer 1.8.2
    - Conclusion: don't install composer/composer 1.8.1
    - Conclusion: don't install composer/composer 1.8.0
    - Conclusion: don't install composer/composer 1.7.3
    - Conclusion: don't install composer/composer 1.7.2
    - Conclusion: don't install composer/composer 1.7.1
    - Conclusion: don't install composer/composer 1.7.0
    - Conclusion: don't install composer/composer 1.7.0-RC
    - Conclusion: don't install composer/composer 1.6.5
    - Conclusion: don't install composer/composer 1.6.4
    - Conclusion: don't install composer/composer 1.6.3
    - Conclusion: don't install composer/composer 1.6.2
    - Conclusion: don't install composer/composer 1.6.1
    - Conclusion: don't install composer/composer 1.6.0
    - Installation request for razorpay/magento ^2.7 -> satisfiable by razorpay/magento[2.7.0].
    - Installation request for magento/product-community-edition 2.2.1 -> satisfiable by magento/product-community-edition[2.2.1].
    - razorpay/magento 2.7.0 requires magento/framework ~102.0.0 -> satisfiable by magento/framework[102.0.0, 102.0.1, 102.0.2].
    - magento/framework 102.0.2 requires composer/composer ^1.6 -> satisfiable by composer/composer[1.6.0, 1.6.0-RC, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.0-RC, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].
    - magento/framework 102.0.1 requires composer/composer ^1.6 -> satisfiable by composer/composer[1.6.0, 1.6.0-RC, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.0-RC, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].
    - magento/framework 102.0.0 requires composer/composer ^1.6 -> satisfiable by composer/composer[1.6.0, 1.6.0-RC, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.0-RC, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6].
    - Conclusion: don't install composer/composer 1.6.0-RC

**Comment by ramth05** [comment]
We already have composer install for Mageno 2.x, The above issue related to server where site hosted.
