### ISSUE TITLE
Class 'Razorpay\Api\Api' not found

### ISSUE THREAD

**Issue by arvind07** [razorpay/razorpay-magento#15]
Hi,
I just integrated this module in my Magento 2.0.7 site. It gave me following error:

`Fatal error: Class 'Razorpay\Api\Api' not found in app\code\Razorpay\Magento\Model\PaymentMethod.php on line 155`

Please check and tell me how to fix.

Thanks

**Comment by 73sl4** [comment]
You need to run `composer dumpautoload -o` command to create a classmap with Razorpay SDK.

**Comment by arvind07** [comment]
Thanks,
It fixed the problem.
