### ISSUE TITLE
The extension is not redirecting the user to payment gateway

### ISSUE THREAD

**Issue by Akshay-Vasu** [razorpay/razorpay-magento#155]
We have installed the razorpay extension for our website built on Magento - 1.9.2.0 

We have created the secret ID and secret key for test instance, using the razorpay admin panel that was provided to us. And we have added the same in the magento configuration

Once we add the item to the cart and try to check out using the razorpay payment method it is taking us to redirection window with a message saying 

**"Please wait...

Do not refresh the page or press back button"**

Can you kindly let me know why this happening

**Comment by ramth05** [comment]
@Akshay-Vasu, have you tried the latest release, steps to install through magento-connect?
https://github.com/razorpay/razorpay-magento-v1/releases

**Comment by ramth05** [comment]
Closing now.
