### ISSUE TITLE
After Install the extension,  Checkout page error  "Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found"

### ISSUE THREAD

**Issue by neethu-sharma** [razorpay/razorpay-magento#156]

**Comment by ramth05** [comment]
@neethu-sharma, how you are installing the it? Can you please try to install from the "code.zip" from the latest release.

**Comment by neethu-sharma** [comment]
I installed version  razorpay-magento 2.7.0
my Magento version 2.3.2

**Comment by ramth05** [comment]
@neethu-sharma , how you installed it? by composer? or through SourceCode.zip file ?

**Comment by neethu-sharma** [comment]
Install   to code.zip  in 
https://github.com/razorpay/razorpay-magento/releases

**Comment by ramth05** [comment]
@neethu-sharma , Can you please post complete error page screen shot here.

**Comment by neethu-sharma** [comment]
Yes sure 
Here http://prntscr.com/otcwpg

**Comment by ramth05** [comment]
@neethu-sharma , can you please clear/clean  the cache and then try out this from terminal
`php bin/magento setup:di:compile`

**Comment by neethu-sharma** [comment]
Note solve

**Comment by ramth05** [comment]
> Note solve

Is it solved?

**Comment by ramth05** [comment]
> > Note solve
> 
> Is it solved?

If not, Please attach the output of `php bin/magento setup:di:compile`

**Comment by ramth05** [comment]
> > > Note solve
> > 
> > @neethu-sharma 
> > Is it solved?
> 
> If not, Please attach the output of `php bin/magento setup:di:compile`

**Comment by gopal2k6** [comment]
I am also facing same issue. 

Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in /home/customer/www/public_html/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /home/customer/www/public_html/app/code/Razorpay/Magento/Controller/Payment/Order.php(34): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /home/customer/www/public_html/generated/code/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor)) #2 /home/customer/www/den in /home/customer/www/public_html/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

**Comment by ramth05** [comment]
> I am also facing same issue.
> 
> Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in /home/customer/www/public_html/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /home/customer/www/public_html/app/code/Razorpay/Magento/Controller/Payment/Order.php(34): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /home/customer/www/public_html/generated/code/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor)) #2 /home/customer/www/den in /home/customer/www/public_html/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

@gopal2k6, which version of plugin you are using and what method you are using to install it?

**Comment by gopal2k6** [comment]
My Magento Version - 2.3.3
ANd
I am using the latest File - 2.8.1

**Comment by gopal2k6** [comment]
I am using code Code-based.

http://prntscr.com/q7vemu


Regards
Gopal Gautam

**Comment by gopal2k6** [comment]
Zip file based

**Comment by gopal2k6** [comment]
Yes After add this line . working fine.

Current code on Razorpay/Magento/Controller/BaseController.php

namespace Razorpay\Magento\Controller;

use Razorpay\Api\Api;
use Razorpay\Magento\Model\Config;
use Magento\Framework\App\RequestInterface;
require_once DIR . "/../../Razorpay/Razorpay.php";

Regards
Gopal Gautam

**Comment by ramth05** [comment]
duplicate #167
