### ISSUE TITLE
Razorpay Error: CURL_ERROR: error setting certificate verify locations: 1.9.3.6

### ISSUE THREAD

**Issue by tosswithim** [razorpay/razorpay-magento#159]
Hello, 
Previously  we have successfully received the payment, suddenly found error Razorpay Error: CURL_ERROR: error setting certificate verify locations: CAfile: /home/xxxxx/public_html/includes/src/ca-bundle.crt CApath: none

Can you help me please

**Comment by ramth05** [comment]
Please try to use latest release from here https://github.com/razorpay/razorpay-magento-v1/releases/tag/1.2.0
