### ISSUE TITLE
Error Capturing the transaction

### ISSUE THREAD

**Issue by arvind07** [razorpay/razorpay-magento#16]
When we apply and discount coupon to the cart, we are not able to place the order. we get this error: http://joxi.net/DmBNnDRuN3yjLm

Please fix it soon.

**Comment by arvind07** [comment]
This issue occurs when the cart total contains decimal numbers like Rs. 1990.10
Works OK in case of round figures like 1990.00

Please fix this issue.

**Comment by arvind07** [comment]
I guess I have found the cause of this bug.
In the Order controller  (https://github.com/razorpay/razorpay-magento/blob/master-2.x/Controller/Payment/Order.php) on line no 41:

`$amount = (int) round($this->getQuote()->getGrandTotal(), 2)*100;`

Here you have type casted the amount to `int`. This is weird. What if the quote total is in decimals like 1234.56?

Changing the above line to:

`$amount = (float) round($this->getQuote()->getGrandTotal(), 2)*100;`

seems to fix the bug for me.

**Comment by captn3m0** [comment]
Thanks a lot for the detailed report. We are looking into this..

Ideally, round($x, 2) would round to 2 decimals of precision, so multiplying by 100 should return a safe int.

**Comment by 73sl4** [comment]
Fixed in #19
