### ISSUE TITLE
Issue Find Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in 

### ISSUE THREAD

**Issue by gopal2k6** [razorpay/razorpay-magento#167]
Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in /home/customer/www/*****/public_html/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /home/customer/www/******/public_html/app/code/Razorpay/Magento/Controller/Payment/Order.php(34): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /home/customer/www/******/public_html/generated/code/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor)) #2 /home/customer/www/den in /home/customer/www/******/public_html/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

**Comment by ramth05** [comment]
> Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in /home/customer/www/_****/public_html/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /home/customer/www/****__/public_html/app/code/Razorpay/Magento/Controller/Payment/Order.php(34): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /home/customer/www/__****/public_html/generated/code/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor)) #2 /home/customer/www/den in /home/customer/www/****_*/public_html/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

@gopal2k6, which version of plugin you are using and what method you are using to install it?

**Comment by gopal2k6** [comment]
My Magento Version - 2.3.3
ANd 
I am using the latest File - 2.8.1

**Comment by ramth05** [comment]
> My Magento Version - 2.3.3
> ANd
> I am using the latest File - 2.8.1

@gopal2k6 , There are two ways to install it composer and zip ? which method you are using to install it?

**Comment by gopal2k6** [comment]
Zip file based

**Comment by ramth05** [comment]
@gopal2k6, can you please check if your installation `Razorpay/Magento/Controller/BaseController.php` contains this line at line no. 6 `require_once __DIR__ . "/../../Razorpay/Razorpay.php";` 

If yes, can you please clear/clean the cache and then try out this from terminal
`php bin/magento setup:di:compile`

**Comment by gopal2k6** [comment]
Yes After add this line . working fine.

Current code on Razorpay/Magento/Controller/BaseController.php

namespace Razorpay\Magento\Controller;

use Razorpay\Api\Api;
use Razorpay\Magento\Model\Config;
use Magento\Framework\App\RequestInterface;
**require_once __DIR__ . "/../../Razorpay/Razorpay.php";**

Regards
Gopal Gautam

**Comment by gopal2k6** [comment]
Thanks for quick help.

**Comment by ramth05** [comment]
@gopal2k6 , as per attached zip file, this line already present in code base. So looks like you are not using proper setup file.

**Comment by gopal2k6** [comment]
http://prntscr.com/q7vn6z Nothing there kindly updates codebase.

**Comment by gopal2k6** [comment]
https://github.com/razorpay/razorpay-magento/releases/tag/2.8.1 update code here

**Comment by ramth05** [comment]
@gopal2k6 , please use `code.zip` file from the release base.
