### ISSUE TITLE
Undefined Index Undefined index: additional_data in /Razorpay/Magento/Model/PaymentMethod.php on line 205 

### ISSUE THREAD

**Issue by JainSoftware** [razorpay/razorpay-magento#169]
Undefined Index Undefined index: additional_data in /Razorpay/Magento/Model/PaymentMethod.php on line 205 .

It's coming in flutter built app using  razorpay in dev mod

**Comment by sodhanii** [comment]
Hey, were you able to find a fix?

**Comment by ramth05** [comment]
@sodhanii , @JainSoftware , we are currently only support web/mobile browsers based magento instance.

**Comment by sodhanii** [comment]
Is there anyway you can work on the API instance?

Best regards,
Aditya

**Comment by ramth05** [comment]
@JainSoftware , we are working on mobile APP based browser supports and may be it solve this issue, will update soon with new release.

**Comment by midhun000** [comment]
@JainSoftware @ramth05 @sodhanii We are facing the same issue. Any updates regarding this?

**Comment by JainSoftware** [comment]
I have created coded custom function o. Razorpay library and it worked .

I can support you but each case can be different and hence it will require
personal intervention .

**Comment by midhun000** [comment]
> intervention

That would be great if you help.

**Comment by midhun000** [comment]
@JainSoftware That would be great if you help.

**Comment by JainSoftware** [comment]
Please connect with us on email, it can be case-specific.

>

**Comment by midhun000** [comment]
@JainSoftware What is the mail id?

**Comment by ramth05** [comment]
@JainSoftware, @midhun000 , the new release supports in APP browsers. Please let us know if you are still facing issues on it.

**Comment by ramth05** [comment]
Closing it for now. Please feel free to re-open it.
