### ISSUE TITLE
Checkout page error

### ISSUE THREAD

**Issue by manojurfriend** [razorpay/razorpay-magento#17]
when going to check out page 
I`m getting this error

Fatal error: Class 'Razorpay\Api\Api' not found in D:\xammp\htdocs\testing\app\code\razorpay\magento\Model\PaymentMethod.php on line 155

**Comment by captn3m0** [comment]
Did you run composer install?

**Comment by manojurfriend** [comment]
Yeah i installed using composer and error is cleared

**Comment by captn3m0** [comment]
Sounds good. Let us know if you face any other issues.
