### ISSUE TITLE
PHP Fatal error:  Interface 'Magento\Framework\App\CsrfAwareActionInterface' not found in Magento 2.2.7?

### ISSUE THREAD

**Issue by arulkec** [razorpay/razorpay-magento#171]
PHP Fatal error:  Interface 'Magento\Framework\App\CsrfAwareActionInterface' not found in /var/www/Magento/app/code/Razorpay/Magento/Controller/Payment/Webhook.php on line 13
**Magento 2.2.7**

**Comment by ramth05** [comment]
> PHP Fatal error:  Interface 'Magento\Framework\App\CsrfAwareActionInterface' not found in /var/www/Magento/app/code/Razorpay/Magento/Controller/Payment/Webhook.php on line 13
> **Magento 2.2.7**

@arulkec , Can you please try to test new release 2.9.1

**Comment by ramth05** [comment]
Already fixed in latest release.
