### ISSUE TITLE
Razorpay payment gateway popup not open but order proceed in magento2 checkout page.

### ISSUE THREAD

**Issue by painal** [razorpay/razorpay-magento#174]
when i am using Razorpay and proceed order via razorpay popup for entering card and UPI not open but redirect to order success page.

**Comment by ramth05** [comment]
@painal , can you please provide more details about this issue. Please share the site url where you testing it as well.

**Comment by ramth05** [comment]
@painal , please update if you are still facing this issue with latest release or we will close this issue in some days.

**Comment by magecomp** [comment]
hi
I have faced same issue in google chrome, popup is not opening while click on razor pay payment.
[image](https://user-images.githubusercontent.com/8856845/95162913-579fb180-07c4-11eb-8f21-fe8790156b0b.png)

Will you please check and let me know.

**Comment by ramth05** [comment]
@magecomp @painal , Please let me know if you are still facing same issue with latest release.

**Comment by ramth05** [comment]
Please use the latest release and let us know if any issues. Closing this issue for now. Please feel free to reopen.
