### ISSUE TITLE
Webhook  Issue on 2.9.3

### ISSUE THREAD

**Issue by gopal2k6** [razorpay/razorpay-magento#178]
Dear Team,

We received No order id WHile Trigger Capture Payment. We found some Bug in Log files. Kindly review. Screenshot Attached

[2020-05-20 20:09:06] main.WARNING: Razorpay Webhook processing started. [] []
[2020-05-20 20:09:06] main.WARNING: Razorpay Webhook processing started for Razorpay payment_id(:pay_EsdeEVx12emycF) [] []
[2020-05-20 20:09:08] main.ERROR: Please check the billing address information. "firstname" is required. Enter and try again. "lastname" is required. Enter and try again. "street" is required. Enter and try again. "city" is required. Enter and try again. "telephone" is required. Enter and try again. "postcode" is required. Enter and try again. "regionId" is required. Enter and try again. [] []
[2020-05-20 21:26:48] main.CRITICAL: No such entity with cartId =  [] []
[2020-05-20 21:36:06] main.WARNING: Razorpay Webhook processing started. [] []
[2020-05-20 21:36:06] main.WARNING: Razorpay Webhook processing started for Razorpay payment_id(:pay_EsdeEVx12emycF) [] []
[2020-05-20 21:36:08] main.ERROR: Please check the billing address information. "firstname" is required. Enter and try again. "lastname" is required. Enter and try again. "street" is required. Enter and try again. "city" is required. Enter and try again. "telephone" is required. Enter and try again. "postcode" is required. Enter and try again. "regionId" is required. Enter and try again. [] []
[2020-05-20 21:41:03] main.CRITICAL: No such entity with cartId =  [] []
[2020-05-20 21:44:58] main.CRITICAL: No such entity with cartId =  [] []
[2020-05-20 22:48:12] main.ERROR: The specified path is not allowed. [] []
[2020-05-21 00:27:03] main.WARNING: Razorpay Webhook processing started. [] []
[2020-05-21 00:27:03] main.WARNING: Razorpay Webhook processing started for Razorpay payment_id(:pay_EsdeEVx12emycF) [] []
[2020-05-21 00:27:04] main.ERROR: Please check the billing address information. "firstname" is required. Enter and try again. "lastname" is required. Enter and try again. "street" is required. Enter and try again. "city" is required. Enter and try again. "telephone" is required. Enter and try again. "postcode" is required. Enter and try again. "regionId" is required. Enter and try again. [] []
[2020-05-21 01:17:12] main.WARNING: Razorpay Webhook processing started. [] []

Regards
Gopal Gautam

**Comment by ramth05** [comment]
@gopal2k6 , Can you please provide replication steps for this one.

**Comment by gopal2k6** [comment]
I just capture Payment from Razerpay dashboard and we did not get order id. Due to issue.. I already shared Log files.

**Comment by ramth05** [comment]
> I just capture Payment from Razerpay dashboard and we did not get order id. Due to issue.. I already shared Log files.

Is this happening for all of your orders? or specific case

**Comment by gopal2k6** [comment]
After Update extension one Transaction was missing.  So I tried to capture payment and No Order Fetch.

**Comment by gopal2k6** [comment]
But i want to know why Order id Not generated Randomly.  Did you find any issue in Current extension ? We found daily 1-2 Transaction.

**Comment by ramth05** [comment]
> But i want to know why Order id Not generated Randomly. Did you find any issue in Current extension ? We found daily 1-2 Transaction.

There are reason of connection/internet on client browser got disconnected as he finished payment and before order get updated by magento/site. So to handle this webhooks comes in picture.  But not sure if your all webhooks failing because of this or just some cases?

**Comment by gopal2k6** [comment]
I will wait  for new Payment for this situation. When comes i will let you know.

**Comment by dipakk2590** [comment]
Hello, I am having the same issue tried installing the latest version extension as well ....still no order ID or Order details found in dashboard nor in database. but payments processed succesfully and customers amount got debited..i have seen this issue with 3 payments which was done through Razorpay only...all other payment options are working fine and showing order details. Please help with the same as its vary difficult to continue without order details or mails from the store.

**Comment by ramth05** [comment]
> Hello, I am having the same issue tried installing the latest version extension as well ....still no order ID or Order details found in dashboard nor in database. but payments processed succesfully and customers amount got debited..i have seen this issue with 3 payments which was done through Razorpay only...all other payment options are working fine and showing order details. Please help with the same as its vary difficult to continue without order details or mails from the store.

@dipakk2590, Can you please share logs of webhooks from your systems for the related payments and related orderId's on dashboard.

**Comment by dipakk2590** [comment]
Hello,

We are not using webhook insted the payment gateway extension is configured on the store to process online method of domestic payments.
have checked all the logs i dint find anything related razorpay in exceptions,debug nor in system logs . only thing was there the extension is depriciated hens i had update the same to latest release on github and the problem is still there.
there are no order ID showing in orders grid or no data available of the order made through razorpay in database as well. if needed i can give my server details you can possibly look into the same.

Thanks

**Comment by ramth05** [comment]
> Hello,
> 
> We are not using webhook insted the payment gateway extension is configured on the store to process online method of domestic payments.
> have checked all the logs i dint find anything related razorpay in exceptions,debug nor in system logs . only thing was there the extension is depriciated hens i had update the same to latest release on github and the problem is still there.
> there are no order ID showing in orders grid or no data available of the order made through razorpay in database as well. if needed i can give my server details you can possibly look into the same.
> 
> Thanks

@dipakk2590 , Please setup webhook to fix this issue.

**Comment by gopal2k6** [comment]
Is there any option to change  Flash Checkout popup    to redirect Checkout like other payment gateway did? We are are still getting No Order ID generated after webhook . This payment gateway are going to  Headache for me. Still i can get Pending order who have any issue. Jo i do manual process where missed this transaction..

**Comment by gopal2k6** [comment]
We are getting Some Price Mismatch issue?

pay_F1Mdgr3Y4qk511 | order_F1MdWRcBn7rBzQ

**Comment by gopal2k6** [comment]
please provide good solution otherwise i will change Payment gateway..

**Comment by gopal2k6** [comment]
https://razorpay.com/docs/payment-gateway/web-integration/hosted/

Some thing like this  But   i want to know this is integrated in Current Magento Extension.

**Comment by ramth05** [comment]
> https://razorpay.com/docs/payment-gateway/web-integration/hosted/
> 
> Some thing like this But i want to know this is integrated in Current Magento Extension.

@gopal2k6 , We are already in testing phase of this feature and let you know when new release available.

**Comment by gopal2k6** [comment]
Is that any option convert quote will convert as a pending Order .. Please provide some patch because we are losing 10k order daily.. woohook also not worked properly ....

**Comment by ramth05** [comment]
> Is that any option convert quote will convert as a pending Order .. Please provide some patch because we are losing 10k order daily.. woohook also not worked properly ....

@gopal2k6 , don't understand requirements here

**Comment by gopal2k6** [comment]
is that Option if popup generate then Automatically pending order created in sales Order with Pending status.  after Success Payment  You can change status Processing... Right now System Created Order after successfully payment..

**Comment by gopal2k6** [comment]
Hope you understand my requirement... This feature we can validate Order which is Missed from Customer.. Right now Unable to find where is customer Order....

**Comment by gopal2k6** [comment]
Any update?????????????????????????????????????

**Comment by ramth05** [comment]
> Hope you understand my requirement... This feature we can validate Order which is Missed from Customer.. Right now Unable to find where is customer Order....

@gopal2k6 , there are other issue when using this approach, like in case of fail payment the cart get empty and user experience will not be good.

**Comment by gopal2k6** [comment]
But Ccavenue do  Great job on this, THey Restored Cart if Payment Failed..

**Comment by gopal2k6** [comment]
Please  Do testing  on Rightway.. Many Customer facing same issue. this is not good for your team and company too.

**Comment by ramth05** [comment]
> Please Do testing on Rightway.. Many Customer facing same issue. this is not good for your team and company too.

@gopal2k6 , do you have any test/ clone site for testing, where we can check this issue?

**Comment by gopal2k6** [comment]
Dear @ramth05 ,

Version 3.0 are  integrated with redirect Payment gateway page option?


Regards
Gopal Gautam

**Comment by ramth05** [comment]
> Dear @ramth05 ,
> 
> Version 3.0 are integrated with redirect Payment gateway page option?
> 
> Regards
> Gopal Gautam

Yes, it is . But you need to check with RZP support to enable the flag for your account.

**Comment by gopal2k6** [comment]
After Update code we are getting error 

Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in /home2/website/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /home2/website/app/code/Razorpay/Magento/Controller/Payment/Order.php(48): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /home2/website/generated/code/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor), Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Mag in /home2/website/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

**Comment by ramth05** [comment]
> After Update code we are getting error
> 
> Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in /home2/website/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /home2/website/app/code/Razorpay/Magento/Controller/Payment/Order.php(48): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /home2/website/generated/code/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor), Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Mag in /home2/website/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

@gopal2k6 , This is still in pre-release and we are testing around it, will make it proper release. Then you can try it.

**Comment by ramth05** [comment]
@gopal2k6 , you can try it now.

**Comment by gopal2k6** [comment]
Yes working but how to enabled Added embedded checkout support

**Comment by harman28** [comment]
@gopal2k6 Could you elaborate on that? What do you need exactly?

**Comment by gopal2k6** [comment]
Thank you ! After updating Latest Release.. It's Seem Working.
