### ISSUE TITLE
Payments Processed But Orders not Placed on Magento 2.3.5 Store

### ISSUE THREAD

**Issue by dipakk2590** [razorpay/razorpay-magento#179]
Hello,

I am having this strange issue of Razorpay Payment Option.
Customer adds orders to checkout and payments gets processed , amount debited and confirmation from bank also received but order not placed or not showing in GRID as well as Payments Dashboard there are no Order ID found...this Missing order ID is Occupied by this GHOST order which is not placed but paid fully by customers.

Kindly Help with the same.

**Comment by offineeds** [comment]
I am also facing the same issue in Magento 2.2.6 from couple of days.

**Comment by ramth05** [comment]
@dipakk2590 , @offineeds , which version of plugin you people using currently? and have you started using web-hook?

**Comment by anuprasadkummali** [comment]
Same when trying with magento 2.3.4

Test mode, after clicking success. it fails 

[2020-06-09 16:37:24] main.CRITICAL: No such entity with orderId =  {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with orderId =  at /opt/magento/public_html/vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []

From browser logs.

(index):1 Failed to load resource: the server responded with a status of 404 ()
misc.js:181 Uncaught TypeError: Cannot read property 'status' of undefined
    at Object.<anonymous> (misc.js:181)
    at fire (jquery.js:3238)
    at Object.fireWith [as rejectWith] (jquery.js:3368)
    at done (jquery.js:9848)
    at XMLHttpRequest.callback (jquery.js:10317)
/rest/default/V1/carts/mine/payment-information:1 Failed to load resource: the server responded with a status of 500 ()

**Comment by offineeds** [comment]
> @dipakk2590 , @offineeds , which version of plugin you people using currently? and have you started using web-hook?

Razorpay 2.9.2 and yes am using Webhook.

**Comment by ramth05** [comment]
> > @dipakk2590 , @offineeds , which version of plugin you people using currently? and have you started using web-hook?
> 
> Razorpay 2.9.2 and yes am using Webhook.

Can you please upgrade it to 2.9.3 and let us know, if still not working. Please provide us credentials of your clone site to look this issue.

**Comment by offineeds** [comment]
> > > @dipakk2590 , @offineeds , which version of plugin you people using currently? and have you started using web-hook?
> > 
> > 
> > Razorpay 2.9.2 and yes am using Webhook.
> 
> Can you please upgrade it to 2.9.3 and let us know, if still not working. Please provide us credentials of your clone site to look this issue.

I had installed older Razorpay through composer, can you guide me how to upgrade it to 2.9.3?

**Comment by ramth05** [comment]
> > > > @dipakk2590 , @offineeds , which version of plugin you people using currently? and have you started using web-hook?
> > > 
> > > 
> > > Razorpay 2.9.2 and yes am using Webhook.
> > 
> > 
> > Can you please upgrade it to 2.9.3 and let us know, if still not working. Please provide us credentials of your clone site to look this issue.
> 
> I had installed older Razorpay through composer, can you guide me how to upgrade it to 2.9.3?

@offineeds , you can remove razorpay by "composer remove [package]" then again install it

**Comment by offineeds** [comment]
> > > > > @dipakk2590 , @offineeds , which version of plugin you people using currently? and have you started using web-hook?
> > > > 
> > > > 
> > > > Razorpay 2.9.2 and yes am using Webhook.
> > > 
> > > 
> > > Can you please upgrade it to 2.9.3 and let us know, if still not working. Please provide us credentials of your clone site to look this issue.
> > 
> > 
> > I had installed older Razorpay through composer, can you guide me how to upgrade it to 2.9.3?
> 
> @offineeds , you can remove razorpay by "composer remove [package]" then again install it

We can't do in live website, there's no way to upgrade existing module through composer?

**Comment by ramth05** [comment]
> > > > > > @dipakk2590 , @offineeds , which version of plugin you people using currently? and have you started using web-hook?
> > > > > 
> > > > > 
> > > > > Razorpay 2.9.2 and yes am using Webhook.
> > > > 
> > > > 
> > > > Can you please upgrade it to 2.9.3 and let us know, if still not working. Please provide us credentials of your clone site to look this issue.
> > > 
> > > 
> > > I had installed older Razorpay through composer, can you guide me how to upgrade it to 2.9.3?
> > 
> > 
> > @offineeds , you can remove razorpay by "composer remove [package]" then again install it
> 
> We can't do in live website, there's no way to upgrade existing module through composer?

you can try `composer update [pakage]`

**Comment by iambaljitdhanoa** [comment]
Hello

We have placed an order but Razorpay transaction Captured but Magento 2.3.0 not placed order.we are using the latest Razorpay extension with using webhook. please let me know how can trigger

**Comment by ramth05** [comment]
> Hello
> 
> We have placed an order but Razorpay transaction Captured but Magento 2.3.0 not placed order.we are using the latest Razorpay extension with using webhook. please let me know how can trigger

@iambaljitdhanoa , in magento admin setting of razorpay, it's listing the webhook url you need to set on razorpay dashboard settings, set same secret both the places and event as "order.paid"

**Comment by iambaljitdhanoa** [comment]
@ramth05 hello Sir

We have used same webhook but displaying error log in razorpay.wc.signature.verify_failed  please let me know how can fix it

**Comment by ramth05** [comment]
> @ramth05 hello Sir
> 
> We have used same webhook but displaying error log in razorpay.wc.signature.verify_failed please let me know how can fix it

@iambaljitdhanoa, Please use same "secret" in both the places, in magento settings and razorpay dashboard webhook settings.

**Comment by iambaljitdhanoa** [comment]
@rabia1305 thank you for a quick reply we have added same api secret key copy to webhook secret key  as well as added same Razorpay dashboard please suggest

**Comment by sagardoshi08** [comment]
Hello Razorpay,

I am phasing the same issue as @dipakk2590. FYI i am using the latest version of Razorpay extension and setup the correct Webhook.

Issue:

I am having this strange issue of Razorpay Payment Option.
Customer adds orders to checkout and payments gets processed , amount debited and confirmation from bank also received but order not placed or not showing in GRID as well as Payments Dashboard there are no Order ID found...this Missing order ID is Occupied by this GHOST order which is not placed but paid fully by customers.

![image](https://user-images.githubusercontent.com/3811874/84593275-09f3e780-ae69-11ea-87f0-234310bed476.png)

Waiting for your reply.

**Comment by dineshprima** [comment]
Hi Team , 

We have same issue in magento 2.2.4 & razorpay extension version is 2.9.3 . We are facing the same problem from last one week time.

When i observed the webhook code that is written by razorpay. they are creating customer accounts for guest orders as well. In that case some of the guest users will use same email as one of the customer already using. In that case we are getting error.

Why you are not checking either it is guest checkout or customer checkout?

When we called razorpay support team , They are giving reply as " There is no issue from their end"... Ya but payment is captured and magento2 order is not created that is a big problem for everyone who is using razorpay as payment gateway.

We need working solution for the above bug.

**Comment by ramth05** [comment]
@dineshprima , we are working on the fix and will update soon.

**Comment by iambaljitdhanoa** [comment]
@dineshprima  we have the short out same problem can you integration webhook in store ???

**Comment by ramth05** [comment]
@iambaljitdhanoa , @dineshprima , We have just added fix and need help to test it.
 Can you please try use this fix https://github.com/razorpay/razorpay-magento/releases/tag/2.9.4 and let us know your feedback.

**Comment by dineshprima** [comment]
> @dineshprima we have the short out same problem can you integration webhook in store ???

Yes , We integrated webhook too in store.

**Comment by dineshprima** [comment]
> @iambaljitdhanoa , @dineshprima , We have just added fix and need help to test it.
> Can you please try use this fix https://github.com/razorpay/razorpay-magento/releases/tag/2.9.4 and let us know your feedback.

I see bug fix for duplicate orders and guest user orders but where is the bug fix for magento2 order id not captured by razorpay... I am pointing this issue..I saw your comments as in latest version 2.9.0 it is resolved but we are using 2.9.3 still issue araised.
Why razorpay not captured order id?

https://github.com/razorpay/razorpay-magento/issues/166

**Comment by sagardoshi08** [comment]
@ramth05 i am also phasing the same issue. Because of that, I have to disable Rezorpay payment from My Magento shop.

**Comment by dineshprima** [comment]
@sagardoshi08 what is the payment gateway that you are using? I am getting headache with this razorpay payment gateway. My superiors always in thought that i am a Very Bad Programmer thats why issue coming. When ever i said it is issue with razorpay they are not even listening my words.

**Comment by sagardoshi08** [comment]
Actually, for India, I am using ccavenue but some time same issue there as well.

**Comment by dineshprima** [comment]
@sagardoshi08 oh , in these cases how you are dealing?

**Comment by ramth05** [comment]
> captured



> > @iambaljitdhanoa , @dineshprima , We have just added fix and need help to test it.
> > Can you please try use this fix https://github.com/razorpay/razorpay-magento/releases/tag/2.9.4 and let us know your feedback.
> 
> I see bug fix for duplicate orders and guest user orders but where is the bug fix for magento2 order id not captured by razorpay... I am pointing this issue..I saw your comments as in latest version 2.9.0 it is resolved but we are using 2.9.3 still issue araised.
> Why razorpay not captured order id?
> 
> #166

@dineshprima , The orderId gets captured with this fix. Can you please test with this new fix release.

**Comment by dineshprima** [comment]
@ramth05 , You are asking to test in production website , Are you sure about the fix ?

**Comment by ramth05** [comment]
> @ramth05 , You are asking to test in production website , Are you sure about the fix ?

@dineshprima , please if possible, test it on clone of production site.

**Comment by dineshprima** [comment]
@ramth05 i tested in this scenario . As a magento customer logged in and selected one product and after payment successful i closed my browser before redirecting to magento website. In razorpay dashboard it is under notes. Now i will check it as normal.

Notes

merchant_order_id
    --

merchant_quote_id
    1716

**Comment by ramth05** [comment]
@dineshprima , As magento only place order after successful payment and order processed from front-end only.  Let me know the paymentId for this? and have you configured the webhook for this. Webhook is used to handle this case. Thanks of testing it. Can you please send me mail directly here "ramprakash.singh@razorpay.com"

**Comment by dineshprima** [comment]
@ramth05 I sent you an email with the order id. We configured webhook.

**Comment by ramth05** [comment]
@dineshprima , closing this issue. Let me know if you still facing any issue and please feel free to reopen it again.

**Comment by vishalpatel19862** [comment]
@ramth05 I am still facing issue where customer has made payment but order is not created on admin panel. i am using razor pay version 3.2.0.

**Comment by ramth05** [comment]
> @ramth05 I am still facing issue where customer has made payment but order is not created on admin panel. i am using razor pay version 3.2.0.

@vishalpatel19862 , Please configure the webhook and check the logs.

**Comment by vishalpatel19862** [comment]
@ramth05 please let me know how to get web hook secret? i am stuck there.

**Comment by ramth05** [comment]
> @ramth05 please let me know how to get web hook secret? i am stuck there.

@vishalpatel19862 please follow https://razorpay.com/docs/webhooks/ and set webhook for `order.paid` event only. The webhook Url can be copied from Magento razorpay settings and then use same secret to setup in magento dashboard as well.

**Comment by vishalpatel19862** [comment]
@ramth05 so for web hook secret field we can set anything we want to set e.g. 'xyzsszcfd' correct?

**Comment by ramth05** [comment]
> @ramth05 so for web hook secret field we can set anything we want to set e.g. 'xyzsszcfd' correct?

Yes, and be sure it must not be disclosed.

**Comment by vishalpatel19862** [comment]
@ramth05 i have set up and tried to place order it dint go to success page, stayed on payment method screen. order is not created in admin panel. i am getting following message in log file.

2020-11-19 05:45:09] main.INFO: Razorpay Webhook processing started. [] []
[2020-11-19 05:45:09] main.INFO: Razorpay Webhook processing started for Razorpay payment_id(:pay_G2uqrqY7MzfL83) [] []
[2020-11-19 05:45:41] main.INFO: Razorpay front-end order processing started quoteID:2022 [] []

**Comment by ramth05** [comment]
> @ramth05 i have set up and tried to place order it dint go to success page, stayed on payment method screen. order is not created in admin panel. i am getting following message in log file.
> 
> 2020-11-19 05:45:09] main.INFO: Razorpay Webhook processing started. [] []
> [2020-11-19 05:45:09] main.INFO: Razorpay Webhook processing started for Razorpay payment_id(:pay_G2uqrqY7MzfL83) [] []
> [2020-11-19 05:45:41] main.INFO: Razorpay front-end order processing started quoteID:2022 [] []

@vishalpatel19862 , the webhook can be used for missing orders, If you are facing issue that after payment it's not redirecting to success page means some other issue. Can you please share the url of site where you testing it?

**Comment by vishalpatel19862** [comment]
@ramth05 after adding web hook i am not getting redirected to success page.earlier i was getting redirected and order was getting created but in some case order is missing. how do you want to me share url?

**Comment by ramth05** [comment]
> @ramth05 after adding web hook i am not getting redirected to success page.earlier i was getting redirected and order was getting created but in some case order is missing. how do you want to me share url?

@vishalpatel19862 , Please send me email here with details of testing url `ramprakash.singh@razorpay.com`

**Comment by adityanvd** [comment]
@ramth05 We are also getting this issue but only for random orders, we are using the latest available extension version(3.4.1) and magento 2.3.3.

**Comment by ramth05** [comment]
> @ramth05 We are also getting this issue but only for random orders, we are using the latest available extension version(3.4.1) and magento 2.3.3.

@adityanvd , Please use webhook for missing orders.

**Comment by bindhuzamorins** [comment]
I am still facing issue where customer has made payment but order is not created on admin panel also order_id is missing in Razor pay dashboard . I am using razor pay version 3.2.1 and my Magento version is 2.4.0

**Comment by ramth05** [comment]
> I am still facing issue where customer has made payment but order is not created on admin panel also order_id is missing in Razor pay dashboard . I am using razor pay version 3.2.1 and my Magento version is 2.4.0

@bindhuzamorins , Please use latest razorpay version 3.6.4, to avoid this issue.
