### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by manojurfriend** [razorpay/razorpay-magento#18]
When i click to razor pay button it gives some validation error and not going to other page .

no error message is shown 
![untitled](https://cloud.githubusercontent.com/assets/20108815/16765518/24b798cc-4852-11e6-97e5-18e612680a95.png)

**Comment by captn3m0** [comment]
Can you see if you have any error messages in the console?

**Comment by manojurfriend** [comment]
GET http://113.193.238.82/testing/razorpay/payment/order?_=1468322990728
	
400 Bad Request
		2.38s	
jquery-....min.js (line 4)
"NetworkError: 400 Bad Request - http://113.193.238.82/testing/razorpay/payment/order?_=1468322990728"

**Comment by manojurfriend** [comment]
It seems something wrong with th key 

i getting an pop up like this after chanign new key and sayting 

Oops! Something went wrong.
The api key provided is invalid
![untitled](https://cloud.githubusercontent.com/assets/20108815/16765752/8b37b1f8-4853-11e6-9883-c335562f62f0.png)

**Comment by captn3m0** [comment]
Please make sure that your keyId begins with `rzp_test_` or `rzp_live_`. Take a look at https://docs.razorpay.com/v1/page/magento for more details.

**Comment by manojurfriend** [comment]
Cleared that can you give demo card details??

**Comment by captn3m0** [comment]
You can try the following:

    MasterCard: 5555555555554444, 5105105105105100 and Visa: 4111111111111111, 4012888888881881, any CVV, any future expiry
