### ISSUE TITLE
Currency other than INR is treated as international payment, even if billing address is Indian

### ISSUE THREAD

**Issue by purpletreesoft** [razorpay/razorpay-magento#183]
We have all products in USD on our website. When we pass USD to your gateway, it treats it as international payment, even though the billing address of the customer is india based.
Due to this, net banking etc are not shown as it is treated as international payment.
This should not happen. This is a defect. Internatinal payment is when the person's billing address is out of India.
Can you do the needful here?

**Comment by ramth05** [comment]
@purpletreesoft,  currency other than INR, the only payment methods are available is cards or paypal.

**Comment by ramth05** [comment]
Closing it as no updates on it. Please check with Razorpay support team for issue related with foreign currency.
