### ISSUE TITLE
main.ERROR: Notice: Undefined index: email in vendor/razorpay/magento/Controller/Payment/Order.php on line 161 [] []

### ISSUE THREAD

**Issue by padhu1980** [razorpay/razorpay-magento#188]
Hello,
I have updated my razorpay code to latest 3.0. But getting this error 
main.ERROR: Notice: Undefined index: email in vendor/razorpay/magento/Controller/Payment/Order.php on line 161 [] []

Please correct this.

**Comment by ChetanGN** [comment]
@padhu1980 Can you please let us know the steps to reproduce this issue! And also please clear your **browser cache** or **disable the cache** and try again. It might be because of the JS file was loading from cache.

**Comment by padhu1980** [comment]
Yes.after clearing cache, this problem resolved. thanks.
