### ISSUE TITLE
Razorpay Api  not found in Magento 2.3.5-P2

### ISSUE THREAD

**Issue by zeekinfo** [razorpay/razorpay-magento#202]
Hi,

am getting an error like this how to fix this

Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in public_html/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /public_html/app/code/Razorpay/Magento/Controller/Payment/Order.php(46): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /public_html/generated/code/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor), Object(Magento\Quote\Model\QuoteManagement\Intercept in //public_html/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

**Comment by ramth05** [comment]
> BaseController

@zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup 

File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
// require in case of zip installation without composer
require_once __DIR__ . "/../../Razorpay/Razorpay.php";

**Comment by zeekinfo** [comment]
I installed manual only i didnt install via composer

**Comment by zeekinfo** [comment]
> > BaseController
> 
> @zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup
> 
> File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
> // require in case of zip installation without composer
> require_once **DIR** . "/../../Razorpay/Razorpay.php";



I installed manual only i didnt install via composer

**Comment by ramth05** [comment]
> > > BaseController
> > 
> > 
> > @zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup
> > File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
> > // require in case of zip installation without composer
> > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> 
> I installed manual only i didnt install via composer

Ok, Can you please confirm if above two lines present on mentioned file ?

**Comment by zeekinfo** [comment]
> > > > BaseController
> > > 
> > > 
> > > @zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup
> > > File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
> > > // require in case of zip installation without composer
> > > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> > 
> > 
> > I installed manual only i didnt install via composer
> 
> Ok, Can you please confirm if above two lines present on mentioned file ?
This is what showing here 

<?php

namespace Razorpay\Magento\Controller;

use Razorpay\Api\Api;
use Razorpay\Magento\Model\Config;
use Magento\Framework\App\RequestInterface;

/**
 * Razorpay Base Controller
 */
abstract class BaseController extends \Magento\Framework\App\Action\Action
{

**Comment by zeekinfo** [comment]
> > > > > BaseController
> > > > 
> > > > 
> > > > @zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup
> > > > File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
> > > > // require in case of zip installation without composer
> > > > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> > > 
> > > 
> > > I installed manual only i didnt install via composer
> > 
> > 
> > Ok, Can you please confirm if above two lines present on mentioned file ?
> > This is what showing here


namespace Razorpay\Magento\Controller;

use Razorpay\Api\Api;
use Razorpay\Magento\Model\Config;
use Magento\Framework\App\RequestInterface;

/**
 * Razorpay Base Controller
 */
abstract class BaseController extends \Magento\Framework\App\Action\Action
{

**Comment by ramth05** [comment]
> > > > > > BaseController
> > > > > 
> > > > > 
> > > > > @zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup
> > > > > File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
> > > > > // require in case of zip installation without composer
> > > > > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> > > > 
> > > > 
> > > > I installed manual only i didnt install via composer
> > > 
> > > 
> > > Ok, Can you please confirm if above two lines present on mentioned file ?
> > > This is what showing here
> 
> namespace Razorpay\Magento\Controller;
> 
> use Razorpay\Api\Api;
> use Razorpay\Magento\Model\Config;
> use Magento\Framework\App\RequestInterface;
> 
> /**
> 
> * Razorpay Base Controller
>   */
>   abstract class BaseController extends \Magento\Framework\App\Action\Action
>   {

@zeekinfo , Can you please confirm which version of plugin you are using it? and to resolve this issue please add these two lines at below this line `namespace Razorpay\Magento\Controller;`

// require in case of zip installation without composer
require_once __DIR__ . "/../../Razorpay/Razorpay.php";

**Comment by zeekinfo** [comment]
> > > > > > > BaseController
> > > > > > 
> > > > > > 
> > > > > > @zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup
> > > > > > File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
> > > > > > // require in case of zip installation without composer
> > > > > > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> > > > > 
> > > > > 
> > > > > I installed manual only i didnt install via composer
> > > > 
> > > > 
> > > > Ok, Can you please confirm if above two lines present on mentioned file ?
> > > > This is what showing here
> > 
> > 
> > namespace Razorpay\Magento\Controller;
> > use Razorpay\Api\Api;
> > use Razorpay\Magento\Model\Config;
> > use Magento\Framework\App\RequestInterface;
> > /**
> > 
> > * Razorpay Base Controller
> >   */
> >   abstract class BaseController extends \Magento\Framework\App\Action\Action
> >   {
> 
> @zeekinfo , Can you please confirm which version of plugin you are using it? and to resolve this issue please add these two lines at below this line `namespace Razorpay\Magento\Controller;`
> 
> // require in case of zip installation without composer
> require_once **DIR** . "/../../Razorpay/Razorpay.php";

am using Magento 2.3.5-P2 but i dont know what  version of Razorpay plugin

**Comment by zeekinfo** [comment]
> > > > > > > > BaseController
> > > > > > > 
> > > > > > > 
> > > > > > > @zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup
> > > > > > > File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
> > > > > > > // require in case of zip installation without composer
> > > > > > > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> > > > > > 
> > > > > > 
> > > > > > I installed manual only i didnt install via composer
> > > > > 
> > > > > 
> > > > > Ok, Can you please confirm if above two lines present on mentioned file ?
> > > > > This is what showing here
> > > 
> > > 
> > > namespace Razorpay\Magento\Controller;
> > > use Razorpay\Api\Api;
> > > use Razorpay\Magento\Model\Config;
> > > use Magento\Framework\App\RequestInterface;
> > > /**
> > > 
> > > * Razorpay Base Controller
> > >   */
> > >   abstract class BaseController extends \Magento\Framework\App\Action\Action
> > >   {
> > 
> > 
> > @zeekinfo , Can you please confirm which version of plugin you are using it? and to resolve this issue please add these two lines at below this line `namespace Razorpay\Magento\Controller;`
> > // require in case of zip installation without composer
> > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> 
> am using Magento 2.3.5-P2 but i dont know what version of Razorpay plugin

Should i give like this?  https://prnt.sc/vg0b3z

**Comment by ramth05** [comment]
@zeekinfo , Can you please download `code.zip` from here and do fresh install again 
https://github.com/razorpay/razorpay-magento/releases/tag/3.2.1

**Comment by zeekinfo** [comment]
> @zeekinfo , Can you please download `code.zip` from here and do fresh install again
> https://github.com/razorpay/razorpay-magento/releases/tag/3.2.1

OK, i will try

**Comment by ramth05** [comment]
> > > > > > > > > BaseController
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @zeekinfo , How you are installing the module in your system. Can you please confirm if in your setup
> > > > > > > > File `//public_html/app/code/Razorpay/Magento/Controller/BaseController.php`, contains these 2 lines at line no. 5 & 6
> > > > > > > > // require in case of zip installation without composer
> > > > > > > > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> > > > > > > 
> > > > > > > 
> > > > > > > I installed manual only i didnt install via composer
> > > > > > 
> > > > > > 
> > > > > > Ok, Can you please confirm if above two lines present on mentioned file ?
> > > > > > This is what showing here
> > > > 
> > > > 
> > > > namespace Razorpay\Magento\Controller;
> > > > use Razorpay\Api\Api;
> > > > use Razorpay\Magento\Model\Config;
> > > > use Magento\Framework\App\RequestInterface;
> > > > /**
> > > > 
> > > > * Razorpay Base Controller
> > > >   */
> > > >   abstract class BaseController extends \Magento\Framework\App\Action\Action
> > > >   {
> > > 
> > > 
> > > @zeekinfo , Can you please confirm which version of plugin you are using it? and to resolve this issue please add these two lines at below this line `namespace Razorpay\Magento\Controller;`
> > > // require in case of zip installation without composer
> > > require_once **DIR** . "/../../Razorpay/Razorpay.php";
> > 
> > 
> > am using Magento 2.3.5-P2 but i dont know what version of Razorpay plugin
> 
> Should i give like this? https://prnt.sc/vg0b3z

Yes

**Comment by ramth05** [comment]
Please use latest release and install it from `code.zip` file. Closing it for now, feel free to reopen it.
