### ISSUE TITLE
Order duplication issue when webhook is enabled

### ISSUE THREAD

**Issue by nathaodedara** [razorpay/razorpay-magento#208]
I had this issue https://github.com/razorpay/razorpay-magento/issues/193, updated the module to the latest version and as said enabled the webhook with events payment.authorized, payment.captured, and order.paid.

Now the issue is if I enable the webhook with these 3 events, some random orders are being placed twice as a duplicate order.

And if I disable the webhook the issue of duplicate order goes away but then the first issue mentioned above of randomly missing order but payment made occurs.

Screenshot of order duplicate issue
![Screenshot_2020-11-09 Orders Operations Sales Magento Admin](https://user-images.githubusercontent.com/61116991/98502694-abe0fa00-2278-11eb-9044-1b095d18a238.png)

**Comment by ramth05** [comment]
@nathaodedara, Yes, there are some duplicate order issue occurring and it's very hard to replicate. If you check the duplicate order issue exist in magento for other payment processors as well.  
We are working on to replicate the issue and exact reason why it's happening. Will get back to you on as we get some work-around on it.

**Comment by nathaodedara** [comment]
I've only one Payment method and that is Razorpay. Please do let me know as soon as possible if there's any work around.

**Comment by nathaodedara** [comment]
Webhooks are not working on localhost, is it possible for webhooks to work in localhost and send event request? If possible do let me know, I'll try debugging and find for a solution if possible.

**Comment by ramth05** [comment]
> I've only one Payment method and that is Razorpay.

Please check things listed here, the issue we are facing also around it only. https://github.com/magento/magento2/issues/13952 ,

**Comment by ramth05** [comment]
> > I've only one Payment method and that is Razorpay.
> 
> Please check things listed here, the issue we are facing also around it only. [magento/magento2#13952](https://github.com/magento/magento2/issues/13952) ,



> Webhooks are not working on localhost, is it possible for webhooks to work in localhost and send event request? If possible do let me know, I'll try debugging and find for a solution if possible.

Nope, you can use some kind of application like `ngrok` to publish your site on internet to handle the webhook locally.

**Comment by ramth05** [comment]
> I've only one Payment method and that is Razorpay. Please do let me know as soon as possible if there's any work around.

@nathaodedara , you can try this our new beta version `https://github.com/razorpay/razorpay-magento/releases/tag/beta-3.3.1` of plugin where Magento order gets created before payment in pending state and can solve webhook dependency and missing order isssue as well. But needs to be tested properly for your site use cases.

**Comment by nathaodedara** [comment]
> > I've only one Payment method and that is Razorpay. Please do let me know as soon as possible if there's any work around.
> 
> @nathaodedara , you can try this our new beta version `https://github.com/razorpay/razorpay-magento/releases/tag/beta-3.3.1` of plugin where Magento order gets created before payment in pending state and can solve webhook dependency and missing order isssue as well. But needs to be tested properly for your site use cases.

Tried this, but while setup:di:compile it is giving the following error:

`Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 76.5 MiBPHP Warning:  Uncaught Exception: Warning: require_once(/var/www/html/vendor/razorpay/magento/Controller/../../Razorpay/Razorpay.php): failed to open stream: No such file or directory in /var/www/html/vendor/razorpay/magento/Controller/BaseController.php on line 6 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/html/vendor/razorpay/magento/Controller/BaseController.php(6): Magento\Framework\App\ErrorHandler->handler(2, 'require_once(/v...', '/var/www/html/v...', 6, Array)
#1 /var/www/html/vendor/razorpay/magento/Controller/BaseController.php(6): require_once()
#2 /var/www/html/vendor/composer/ClassLoader.php(444): include('/var/www/html/v...')
#3 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/v...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Razorpay\\Magent...')
#5 [internal function]: spl_autoload_call('Razorpay\\Magent...')
#6 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(1 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php on line 61
PHP Fatal error:  main(): Failed opening required '/var/www/html/vendor/razorpay/magento/Controller/../../Razorpay/Razorpay.php' (include_path='/var/www/html/generated/code:/var/www/html/generated/code:/var/www/html/vendor/magento/zendframework1/library:.:/usr/share/php') in /var/www/html/vendor/razorpay/magento/Controller/BaseController.php on line 6
`

Permission was given multiple times, so giving permission didn't help. I hope this can help you improve the version quality.

**Comment by nathaodedara** [comment]
> > I've only one Payment method and that is Razorpay.
> 
> Please check things listed here, the issue we are facing also around it only. [magento/magento2#13952](https://github.com/magento/magento2/issues/13952) ,

This is not a Magento issue because the duplicate order is being placed at exactly the same time and also event 'sales_order_place_before' and adding code to check if order with quote id already exists but this isn't helping too. I think this is an issue with something from your module Webhook but not able to find where's an issue. This is really annoying please do suggest a solution if you have any. Thank you.

**Comment by Manak** [comment]
Just went through this. I'm on v2.9 of the module and am facing this exact issue. No clue on how to resolve this. 
It looks like there might be a case where a webhook is sending a request twice instead of a single time. The issue is I am not able to replicate the problem consistently.

**Comment by ramth05** [comment]
@Manak , can you please try the latest release V3.3.0.

**Comment by santhoshp** [comment]
@ramth05 The duplicate order issue exists in V3.3.0. This happens only if I enable the webhook.

**Comment by somunelavalli** [comment]
We are also facing the duplicate order issue and on the Successful page showing different order number and Cart is not clearing the product after purchase. if we enable the Webhooks.
For some Customers After making the payment, it showing like"Quote id is Not Available"
For me, it is generated almost 9 duplicate orders.


![Product in Cart](https://user-images.githubusercontent.com/47572851/108455435-48f9f880-7294-11eb-8e46-ae06e549e67e.PNG)
![WhatsApp Image 2021-02-17 at 5 51 57 AM](https://user-images.githubusercontent.com/47572851/108455442-4a2b2580-7294-11eb-95e5-65b1251d2783.jpeg)
![Order_Creation_Automatic1](https://user-images.githubusercontent.com/47572851/108455444-4ac3bc00-7294-11eb-8cb2-38da7487ff8d.PNG)
![Order_Creation_Automatic](https://user-images.githubusercontent.com/47572851/108455446-4ac3bc00-7294-11eb-89a6-fdb49bdf26e9.PNG)

**Comment by ramth05** [comment]
@nathaodedara , Please try latest release 3.4.1 with delay configured for webhook execution. It must solve this issue.

**Comment by shixiujuan** [comment]
Hi All, May I know how the problem was finally solved? We only use Razorpay for the payment, and currently facing the same problems. has also lost many customers and urgently need to fix this problem. Thank you.

**Comment by ramth05** [comment]
@shixiujuan , Please use latest plugin 3.6.2 to resolve above issues.

**Comment by shixiujuan** [comment]
Thank you so much for advice. we just updated the plugin verson to 3.6.3 this morning, and still experiencing this problem. 

![image](https://user-images.githubusercontent.com/88638550/128657879-6e9e5a85-3f83-4a0c-893f-9f60fa3590c2.png)

**Comment by shixiujuan** [comment]
Sorry, we updated to 3.6.2 Version. still experienced this problem, tested in test environment.

**Comment by ramth05** [comment]
> Sorry, we updated to 3.6.2 Version. still experienced this problem, tested in test environment.

@shixiujuan , A per our records orderId recored as `000000158`. Please check your system or magento logs for any error or issue if it's not reflecting in Magento dashboard.

**Comment by shixiujuan** [comment]
Thank you so much. but their was no log information about 158. 
![image](https://user-images.githubusercontent.com/88638550/128668476-422e8525-fb9c-4410-a00c-752ae0d2edcc.png)
