### ISSUE TITLE
Feature Request - Subscriptions and Recurring Payment

### ISSUE THREAD

**Issue by lokeshvnaik** [razorpay/razorpay-magento#209]
Need below features with Magento 2 Razorpay payment gateway

1. Create and manage subscription products
2. Capture secure recurring payments based on billing cycle
3. Schedule the subscription period of any time interval and frequency
4. Supports Email Notifications (e.g. notification before expiry period)
5. Renew a subscription
6. Cancel a subscription

Are there any other 3rd party extension which supports above features with Razorpay payment gateway?

**Comment by yashgit891** [comment]
@lokeshvnaik we have a Magento subscription plugin for this, please check it out.
