### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by mhd2arif** [razorpay/razorpay-magento#210]
Hi there,

We are struggling to place magento order with razorpay method in API level for mobile application. Also we are not able to find any relevant document related to the REST API flow for the mobile app and creating orders on Magento.

Even for V1/carts/mine/payment-information we are unable to determine request param values order_id, rzp_payment_id and rzp_signature.

Could you let us know about the Rest API level flow?

**Comment by ramth05** [comment]
@mhd2arif , How you are taking payment using API? 

`Even for V1/carts/mine/payment-information we are unable to determine request param values order_id, rzp_payment_id and rzp_signature.` These params are related with front-end order processing and required user to complete the payment manually. So when user complete the payments through razorpay checkout.js in callback url the razorpay sent these params.

**Comment by mhd2arif** [comment]
@ramth05 
Thanks for the reply.

We over came our scenario by creating a Rest api to generate razorpay order_id  as mentioned in 6th step of the below reference.
REF:-  https://razorpay.com/docs/payment-gateway/react-native-integration/standard/android/
And stored it in catalog session.
then after the 7th step in reference we passed payment id and signature to V1/carts/mine/payment-information.
That worked.
