### ISSUE TITLE
Magento2 Duplicate Order Issue

### ISSUE THREAD

**Issue by dineshmanne** [razorpay/razorpay-magento#211]
I am using Magento 2.3.5 p2 version  , Razorpay version 3.2.1 . Customer paying for one order but in magento it is creating two orders when webhook is enabled.

In last 4 days it happened for 2 orders on same day and 1 order on another day. Do you have any resolution for it?

**Comment by dineshmanne** [comment]
I think that Razorpay Webhook and Front end webhook hitting at same time. Can we add some sleep time to get Active Quote Status in backend webhook. So that we can avoid duplicate orders. Will that work ?

**Comment by ramth05** [comment]
@dineshmanne, Added some fix in Razorpay version 3.2.2 for same. Can you please try it and confirm if still issue persist.

**Comment by ramth05** [comment]
@dineshmanne , please let me know, if still you are facing this issue with new version of plugin.

**Comment by ramth05** [comment]
@dineshmanne , Closing this issue now. Please reopen it if issue still exist.
