### ISSUE TITLE
Razorypay order amount is less than that of Magento Order 

### ISSUE THREAD

**Issue by mandarzope** [razorpay/razorpay-magento#216]
Steps to reproduce

1. Add one item to cart and proceed to checkout (Cart total is X)
2. Click PlaceOrder using Razorpay payment method.
3. Let the Razorpay popup open and do not place order
4. In the new tab open website again and add more items to the cart (Cart total is 3X)
5. Come back to previous tab and make payment
Razorpay has captured amount of X but the order is placed of 3X.

**Comment by ramth05** [comment]
@mandarzope , thanks for helping on testing and pointing out this issue. This looks like a bug, we are working to fix it.

**Comment by ramth05** [comment]
@mandarzope , the fix is release with this V3.3.0.
