### ISSUE TITLE
Razorpay Magento 2.X plugin giving error on calling Graphql placeOrder query.

### ISSUE THREAD

**Issue by ankittparikh** [razorpay/razorpay-magento#218]
Response of GraphQL placeOrder query 
```
{
  "errors": [
    {
      "message": "Unable to place order: Razorpay Error: Notice: Undefined index: paymentMethod in /opt/bitnami/apps/magento/htdocs/app/code/Razorpay/Magento/Model/PaymentMethod.php on line 223.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "placeOrder"
      ]
    }
  ],
  "data": {
    "placeOrder": null
  }
}
```

**Comment by ramth05** [comment]
@ankittparikh , Currently Razorpay plugin don't support GraphQL order placement.

**Comment by Afreen-Cedcoss** [comment]
When will the razorpay graphql support will be provided

**Comment by ramth05** [comment]
> When will the razorpay graphql support will be provided

@Afreen-Cedcoss , can you please help me how you are using GraphQL to place the order. 
Like curl request or  payload and url you are using for same. To understand the use case.

**Comment by ramth05** [comment]
@ankittparikh ,  Can you please let me know how you are taking/collecting razorpay payments with GraphQL?

**Comment by Afreen-Cedcoss** [comment]
> > When will the razorpay graphql support will be provided
> 
> @Afreen-Cedcoss , can you please help me how you are using GraphQL to place the order.
> Like curl request or payload and url you are using for same. To understand the use case.

Using it as a payload

**Comment by ramth05** [comment]
> > > When will the razorpay graphql support will be provided
> > 
> > 
> > @Afreen-Cedcoss , can you please help me how you are using GraphQL to place the order.
> > Like curl request or payload and url you are using for same. To understand the use case.
> 
> Using it as a payload

@Afreen-Cedcoss, I just want to check how you are accepting Razorpay payments? with GaphQL before palceOrder call?
Are you using any front-end APP for same?

**Comment by ankittparikh** [comment]
> @ankittparikh , Can you please let me know how you are taking/collecting Razorpay payments with GraphQL?

We created our own Razarpay plugin for Magento. So steps we use to receive payment is as follows:
1. We create an order (using placeOrder mutation) in Pending Status using Magento GraphQL query from our react frontend app.  which returns order_id in response
2. We then initiate Razorpay Widget on react app using same order_id

In the above scenario, we are using a payment method as checkmo for Magento. 
When can we expect a Razorpay plugin for Magento which is compatible with Magento GraphQL ?

**Comment by ramth05** [comment]
@ankittparikh , We are in testing phase of GraphQL support #240. Will update you soon when it released.

**Comment by abhilashiic** [comment]
Can we test this feature? It will be very helpful to know the tentative timeline for this feature.

**Comment by ramth05** [comment]
> Can we test this feature? It will be very helpful to know the tentative timeline for this feature.

@abhilashiic , It's already in QA and will be released by next week.

**Comment by ramth05** [comment]
@abhilashiic, We have released 3.6.0 with GraphQL.

**Comment by ankittparikh** [comment]
Razorpay working with 3.6.0 update.

**Comment by ashokraman** [comment]
I am getting this error from vue-storefront 2 version - Unable to place order - Razor payment details missing - Path: placeOrder - related issue?
