### ISSUE TITLE
Want to save the actual amount paid. 

### ISSUE THREAD

**Issue by drksl** [razorpay/razorpay-magento#220]
There are some offer discounts running on Razorpay dashboard. So when the customer reaches to pay for the order he/she can still take further discount, so ie. instead of paying 9000 they end up paying 8000. But on Magento DB 9000 is getting captured which is quite a hassle while initiating refund. Can you please help to save the actual payment paid by the customer. 

Thank you.

**Comment by yashgit891** [comment]
@drksl this is resolved in latest release, please check.
