### ISSUE TITLE
Problem with 3.3.0 version of razorpay Plugin

### ISSUE THREAD

**Issue by akash-innov** [razorpay/razorpay-magento#221]
Hi, I am using,  Magento **ver. 2.3.5-p1** I am getting 500 error on the checkout page after installing the latest version of Razorpay plugin 3.3.0.
But it's working totally fine when I am using an older version of Razorpay plugin 2.9.2.

What might be the possible reason for this? Need help.

**Comment by ramth05** [comment]
@akash-innov , Can you please try the latest release `3.4.1`.
