### ISSUE TITLE
webhook error 

### ISSUE THREAD

**Issue by zeekinfo** [razorpay/razorpay-magento#226]
HI

am getting some webhook error how to fix this 

https://worldwideaj.com/razorpay/payment/webhook

Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in /home/473059.cloudwaysapps.com/djdaccjsak/public_html/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /home/473059.cloudwaysapps.com/djdaccjsak/public_html/app/code/Razorpay/Magento/Controller/Payment/Webhook.php(86): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /home/473059.cloudwaysapps.com/djdaccjsak/public_html/generated/code/Razorpay/Magento/Controller/Payment/Webhook/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Webhook->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor) in /home/473059.cloudwaysapps.com/djdaccjsak/public_html/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

**Comment by ramth05** [comment]
@zeekinfo , Which version of plugin you are using ? can you please upgrade to latest release 3.3.1
