### ISSUE TITLE
Latest Razorpay plugin web hook erro

### ISSUE THREAD

**Issue by prabakar1978** [razorpay/razorpay-magento#227]
https://ezekiahfrancis.in/razorpay/payment/webhook

TypeError: Return value of Razorpay\Magento\Controller\Payment\Webhook::getPostData() must be of the type array, null returned in /home/ezekiahf/public_html/prodshop/vendor/razorpay/magento/Controller/Payment/Webhook.php:369 Stack trace: #0 /home/ezekiahf/public_html/prodshop/vendor/razorpay/magento/Controller/Payment/Webhook.php(117): Razorpay\Magento\Controller\Payment\Webhook->getPostData() #1 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(58): Razorpay\Magento\Controller\Payment\Webhook->execute() #2 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(138): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->___callParent('execute', Array) #3 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->Magento\Framework\Interception\{closure}() #4 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute(Object(Razorpay\Magento\Controller\Payment\Webhook\Interceptor), Object(Closure)) #5 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(153): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->Magento\Framework\Interception\{closure}() #6 /home/ezekiahf/public_html/prodshop/generated/code/Razorpay/Magento/Controller/Payment/Webhook/Interceptor.php(23): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->___callPlugins('execute', Array, Array) #7 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/App/Action/Action.php(111): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->execute() #8 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #9 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(138): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->___callParent('dispatch', Array) #10 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(153): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #11 /home/ezekiahf/public_html/prodshop/generated/code/Razorpay/Magento/Controller/Payment/Webhook/Interceptor.php(32): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->___callPlugins('dispatch', Array, Array) #12 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/App/FrontController.php(186): Razorpay\Magento\Controller\Payment\Webhook\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #13 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Razorpay\Magento\Controller\Payment\Webhook\Interceptor)) #14 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) #15 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) #16 /home/ezekiahf/public_html/prodshop/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #17 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #18 /home/ezekiahf/public_html/prodshop/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #19 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #20 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #21 /home/ezekiahf/public_html/prodshop/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL) #22 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #23 /home/ezekiahf/public_html/prodshop/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #24 /home/ezekiahf/public_html/prodshop/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #25 /home/ezekiahf/public_html/prodshop/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #26 {main}

**Comment by ramth05** [comment]
@prabakar1978, how you using the webhook?

**Comment by prabakar1978** [comment]
Hi,
I am getting the below email daily from Razorpay after this my webhook got disabled in the RazorPay dashboard.  so i tried to execute the my webhook from browser and to see if there is any problem with the same.  

Hi, We have been experiencing webhook delivery failure for past 24 hours while trying to hit the live webhook url - https://ezekiahfrancis.in/razorpay/payment/webhook. As noted in our documentation, we have disabled your webhook as a precaution. You can re-enable the webhook again by visiting the Dashboard and going to the webhooks tab.

**Comment by ramth05** [comment]
> Hi,
> I am getting the below email daily from Razorpay after this my webhook got disabled in the RazorPay dashboard. so i tried to execute the my webhook from browser and to see if there is any problem with the same.
> 
> Hi, We have been experiencing webhook delivery failure for past 24 hours while trying to hit the live webhook url - https://ezekiahfrancis.in/razorpay/payment/webhook. As noted in our documentation, we have disabled your webhook as a precaution. You can re-enable the webhook again by visiting the Dashboard and going to the webhooks tab.

@prabakar1978 , This will only work for Server to server call when Razorpay hit the webhook endpoint. So if you execute it manually then this kind of errors you will see.
