### ISSUE TITLE
Webhook disabled daily

### ISSUE THREAD

**Issue by prabakar1978** [razorpay/razorpay-magento#233]
Hi,

My webhook in RazorPay daily got deactivated and i need to activate daily.  Is it the problem with RazorPay or with my RazorPay-magento2 plugin.  Please share some input on the same

www.ezekiahfrancis.in is my domain

Hi, We have been experiencing webhook delivery failure for past 24 hours while trying to hit the live webhook url - https://ezekiahfrancis.in/razorpay/payment/webhook. As noted in our documentation, we have disabled your webhook as a precaution. You can re-enable the webhook again by visiting the Dashboard and going to the webhooks tab.

**Comment by ramth05** [comment]
> Hi,
> 
> My webhook in RazorPay daily got deactivated and i need to activate daily. Is it the problem with RazorPay or with my RazorPay-magento2 plugin. Please share some input on the same
> 
> [www.ezekiahfrancis.in](http://www.ezekiahfrancis.in) is my domain
> 
> Hi, We have been experiencing webhook delivery failure for past 24 hours while trying to hit the live webhook url - https://ezekiahfrancis.in/razorpay/payment/webhook. As noted in our documentation, we have disabled your webhook as a precaution. You can re-enable the webhook again by visiting the Dashboard and going to the webhooks tab.

@prabakar1978 ,  Please use same secret which you setting on RZP dashboard under magento webhook secret field.

**Comment by prabakar1978** [comment]
> > Hi,
> > My webhook in RazorPay daily got deactivated and i need to activate daily. Is it the problem with RazorPay or with my RazorPay-magento2 plugin. Please share some input on the same
> > [www.ezekiahfrancis.in](http://www.ezekiahfrancis.in) is my domain
> > Hi, We have been experiencing webhook delivery failure for past 24 hours while trying to hit the live webhook url - https://ezekiahfrancis.in/razorpay/payment/webhook. As noted in our documentation, we have disabled your webhook as a precaution. You can re-enable the webhook again by visiting the Dashboard and going to the webhooks tab.
> 
> @prabakar1978 , Please use same secret which you setting on RZP dashboard under magento webhook secret field.

thanks for your input.  But I am pretty sure my webhook secret really same.  Do we need any mechanism to test whether my webhook  is synced with RazorPay or not.

**Comment by ramth05** [comment]
@prabakar1978 , Please check the logs present under `var/log/Razorpay/`, To verify what kind of errors reported here.

**Comment by prabakar1978** [comment]
> @prabakar1978 , Please check the logs present under `var/log/Razorpay/`, To verify what kind of errors reported here.

For webhook disablement i don't see any logs in this directory.  But i can see the logs for the regular transactions only

-rw-rw-r-- 1 ezekiahf ezekiahf  190 Feb 20 06:49 rzp_2021_02_20.log
-rw-rw-r-- 1 ezekiahf ezekiahf 1.5K Feb 22 04:43 rzp_2021_02_22.log
-rw-rw-r-- 1 ezekiahf ezekiahf  906 Feb 23 05:59 rzp_2021_02_23.log
-rw-rw-r-- 1 ezekiahf ezekiahf  811 Feb 24 02:00 rzp_2021_02_24.log
ezekiahf@server.ezekiahfrancis.in [Razorpay]# pwd
var/log/Razorpay

**Comment by ramth05** [comment]
> > @prabakar1978 , Please check the logs present under `var/log/Razorpay/`, To verify what kind of errors reported here.
> 
> For webhook disablement i don't see any logs in this directory. But i can see the logs for the regular transactions only
> 
> -rw-rw-r-- 1 ezekiahf ezekiahf 190 Feb 20 06:49 rzp_2021_02_20.log
> -rw-rw-r-- 1 ezekiahf ezekiahf 1.5K Feb 22 04:43 rzp_2021_02_22.log
> -rw-rw-r-- 1 ezekiahf ezekiahf 906 Feb 23 05:59 rzp_2021_02_23.log
> -rw-rw-r-- 1 ezekiahf ezekiahf 811 Feb 24 02:00 rzp_2021_02_24.log
> [ezekiahf@server.ezekiahfrancis.in](mailto:ezekiahf@server.ezekiahfrancis.in) [Razorpay]# pwd
> var/log/Razorpay

@prabakar1978 , please send these logs here `ramprakash.singh@razorpay.com`

**Comment by ramth05** [comment]
This was because of SSL certificate not valid.
