### ISSUE TITLE
Cart and Checkout page not working after installing the latest version of Razorpay magento plugin  on Magento ver. 2.3.5-p2

### ISSUE THREAD

**Issue by sharmahoney80** [razorpay/razorpay-magento#234]
The checkout n cart pages previously was working fine, but afer installing the plugin these pages are not working , got blank

**Comment by ramth05** [comment]
> The checkout n cart pages previously was working fine, but afer installing the plugin these pages are not working , got blank

@sharmahoney80 , Please let me know which version of plugin you are using and the site link please.

**Comment by ramth05** [comment]
@sharmahoney80 , Please try latest release.
