### ISSUE TITLE
Razorpay Version 3.4.0 giving Error while accessing admin panel in Magento v 2.4.2

### ISSUE THREAD

**Issue by vinaykumar9999** [razorpay/razorpay-magento#238]
Hi

Facing the following issue on Magento 2.4.2 with Razorpay Version 3.4.0
Error is coming while accessing admin panel. Any workaround for this issue ?

main.CRITICAL: Error: Call to undefined method Magento\Framework\Logger\LoggerProxy::setHandlers() in /home/public_html/vendor/razorpay/magento/Controller/Payment/Order.php:61
Stack trace:
#0 /public_html/generated/code/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Backend\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor), Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Magento\Framework\App\Cache\Proxy), Object(Magento\Sales\Model\OrderRepository\Interceptor), Object(Magento\Framework\Logger\LoggerProxy), Object(Razorpay\Magento\Model\LogHandler))

Please help in solving the issue.

**Comment by ramth05** [comment]
#230 , @vinaykumar9999. it's duplicate issue. The fix already applied in master. Will provide the release soon.
