### ISSUE TITLE
Cart not get cleared

### ISSUE THREAD

**Issue by karthickannan** [razorpay/razorpay-magento#24]
We are facing this issue in our Magento 1.x environment. Our environment details are as follows:

Magento version - 1.9.2.4
HTTP server - nGinx
OS - CentOS

With a successful test order the customer's cart is not getting cleared.

**Comment by captn3m0** [comment]
Can you tell us the following:

1. What is the razorpay plugin version?
2. If you are using a third-party checkout?

**Comment by karthickannan** [comment]
1) RazorPay version - 1.1.9
2) Yes we have customised the checkout on our own. No third party plug-ins are used

**Comment by karthickannan** [comment]
Is there any update on this?

**Comment by karthickannan** [comment]
@73sl4 @captn3m0 

Is there any update on this? It has been two months since the last comment.

**Comment by mayankamencherla** [comment]
Tested this on our latest version - cart gets cleared. 
Closing issue. 

Link to latest release: https://github.com/razorpay/razorpay-magento/releases/tag/1.1.22
