### ISSUE TITLE
PHP Fatal error:  main(): Failed opening required Installing razorpay/magento (3.5.0)

### ISSUE THREAD

**Issue by harendraprajapati** [razorpay/razorpay-magento#247]
PHP Warning:  Uncaught Exception: Warning: require_once(/vendor/razorpay/magento/Observer/../../Razorpay/Razorpay.php): failed to open stream: No such file or directory in /vendor/razorpay/magento/Observer/AfterConfigSaveObserver.php on line 6 in /vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /vendor/razorpay/magento/Observer/AfterConfigSaveObserver.php(6): Magento\Framework\App\ErrorHandler->handler(2, 'require_once(/c...', '/chroot/home/ad...', 6, Array)
#1 /vendor/razorpay/magento/Observer/AfterConfigSaveObserver.php(6): require_once()
#2 /vendor/composer/ClassLoader.php(444): include('/chroot/home/ad...')
#3 /vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/chroot/home/ad...')
#4 [internal function]: Composer\Au in /vendor/magento/framework/App/ErrorHandler.php on line 61
PHP Fatal error:  main(): Failed opening required '/vendor/razorpay/magento/Observer/../../Razorpay/Razorpay.php' (include_path='/generated/code:/chroot/home/generated/code:/chroot/home/vendor/magento/zendframework1/library:.:/opt/remi/php73/root/usr/share/pear:/opt/remi/php73/root/usr/share/php:/usr/share/pear:/usr/share/php') in /chroot/vendor/razorpay/magento/Observer/AfterConfigSaveObserver.php on line 6

**Comment by ramth05** [comment]
@harendraprajapati , Can you please try the latest release 3.5.1 and let us know if still there are any issue.

**Comment by ramth05** [comment]
@harendraprajapati , please let us know if you are facing any issue with latest release.

**Comment by harendraprajapati** [comment]
Working Fine As Expected w release 3.5.1. Thanks.
