### ISSUE TITLE
Registered Customer Email is not auto-filled

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-magento#25]
Non registered customer email appears in checkout, but the same does not happen if the customer is already registered.

![4690df84ffcc4b0498b91a744d9b9c5d](https://cloud.githubusercontent.com/assets/584253/18355372/821aa7c0-7606-11e6-9ba7-a90ac4f6a8e5.png)

Magento Version: 2.1

**Comment by mayankamencherla** [comment]
https://github.com/razorpay/razorpay-magento/pull/67
