### ISSUE TITLE
Reg PDF books order and Hard copies order confirmation

### ISSUE THREAD

**Issue by prabakar1978** [razorpay/razorpay-magento#255]
Hi,

In My shopping cart if someone is ordering pdf books alone then after the successful order status got updated with Complete so end user can download pdf

If someone is ordering pdf books and hard copy books then pdf books are not able to download since the order status will marked as Processing only due to that user is not able download the books immediately.  Could you please change the razorpay plugin to pdf books order status alone as success
![order](https://user-images.githubusercontent.com/25123226/122397894-ff49c200-cf96-11eb-8538-74c2e2d0920e.jpg)

**Comment by yashgit891** [comment]
@prabakar1978 status is at a order level and not product level so this is a limitation from platform.
