### ISSUE TITLE
fatal error on saving razorpay configuration from backend

### ISSUE THREAD

**Issue by vinaychhabra** [razorpay/razorpay-magento#256]
[
![razorpay](https://user-images.githubusercontent.com/21859132/122602943-43b98880-d091-11eb-99a1-34919fe296e1.png)
](url)
I got this fatal error on saving razorpay payment method configuration from backend.
I had installed it through zip file.

**Comment by ramth05** [comment]
> [ ![razorpay](https://user-images.githubusercontent.com/21859132/122602943-43b98880-d091-11eb-99a1-34919fe296e1.png) ](url)
> I got this fatal error on saving razorpay payment method configuration from backend.
> I had installed it through zip file.

@vinaychhabra , which version you are trying to install? and which zip file you are using?

**Comment by vinaychhabra** [comment]
@ramth05 3.5.1 of razorpay and magento version is 2.3.5-p1. Downloaded  zip from git.

**Comment by ramth05** [comment]
@vinaychhabra , please use latest release 3.6.1 and use `code.zip` file for zip installation.

**Comment by vinaychhabra** [comment]
Ok thanks
