### ISSUE TITLE
Error on save admin setting

### ISSUE THREAD

**Issue by dev-amitsaini** [razorpay/razorpay-magento#262]
Error showing in a log file on save payment method configuration setting. After upgrade extension from 3.4.1 to 3.6.2 by the composer.
**Error showing in the log file:**
main.CRITICAL: Error: Class '**Razorpay\Api\Webhook**' not found in public_html/vendor/razorpay/razorpay/src/Api.php:67

**Comment by ramth05** [comment]
@dev-amitsaini ,  can you please upgrade this as well "razorpay/razorpay" through composer with latest one. Looks it's picking old version of SDK.
https://github.com/razorpay/razorpay-php

**Comment by dev-amitsaini** [comment]
Thank you @ramth05.
After upgrade "razorpay/razorpay" it's working fine.
