### ISSUE TITLE
Magento Backend save config issue

### ISSUE THREAD

**Issue by prashantextcommerce** [razorpay/razorpay-magento#263]
I installed the Magento 2 plugin in my store. I successfully installed the Magento 2 plugin version 3.6.2 but I am getting below error while Save Razorpay pay payment config setting from Magento Backend.

Undefined index: razorpay in /app/code/Razorpay/Magento/Observer/AfterConfigSaveObserver.php

I tried to solve as per the given solution docs in the troubleshooting section https://razorpay.com/docs/payment-gateway/ecommerce-plugins/magento/2.x/#troubleshooting
But the issue was not resolved.

**Comment by ramth05** [comment]
@prashantextcommerce , How you have installed the plugin. by using "code.zip" or just from the source code.
Please try to run `setup:di:compile` and check for the errors.

**Comment by prashantextcommerce** [comment]
I tried using both composer and "code.zip" but the error was not resolved even after run bin/magento setup:di:compile

**Comment by ramth05** [comment]
> I tried using both composer and "code.zip" but the error was not resolved even after run bin/magento setup:di:compile

@prashantextcommerce , what version of magento you are using and can you please share the output of above command.

**Comment by prashantextcommerce** [comment]
I am using Magento ver. 2.4.2-p1
I attached screenshots of backend config error and di compile output.
<img width="1647" alt="admin_config_error" src="https://user-images.githubusercontent.com/25030256/126797072-9005004f-31b2-48cd-9ab4-e299ffa1964a.png">
<img width="593" alt="di_complie" src="https://user-images.githubusercontent.com/25030256/126797161-aaef4a43-1734-4b3f-b043-7318542da711.png">

**Comment by yashgit891** [comment]
These issues have been resolved as well as installation has been tested on this specific version, so closing this thread.
