### ISSUE TITLE
Razorpay Extended Config Data Missing

### ISSUE THREAD

**Issue by sachin000** [razorpay/razorpay-magento#267]
- Front end integration requires Merchant Name & API key ID to initiate Razorpay checkout, this config should come via Extended config query.
- I have created PR for the same , please merge it asap.
https://github.com/razorpay/razorpay-magento/pull/266

**Comment by sachin000** [comment]
Fix :
https://github.com/razorpay/razorpay-magento/pull/268

**Comment by sachin000** [comment]
https://devdocs.magento.com/guides/v2.4/graphql/develop/extend-existing-schema.html
Re Implementation As per above document ,
Added Additional Config data in new /etc/graphql/di.xml
Tested & Working

![image](https://user-images.githubusercontent.com/6098456/128466944-09c0bba4-ae16-464d-94a3-acfa16c40c24.png)

**Comment by yashgit891** [comment]
Closing this thread as PR is merged.
