### ISSUE TITLE
Need a way to disable auto sending email of Invoice to customer after placing order

### ISSUE THREAD

**Issue by vinaykumar9999** [razorpay/razorpay-magento#277]
Hi

Please help me in solving the following issue.

Please select the Payment Action Option to "Authorize and Capture"

Screenshot : https://prnt.sc/1stim9z

Only this option is sending automatic Emails of Invoice to Customer Just after placing the order.
It is best if it is generating Invoices only, rather then sending emails directly to customers.

How to stop sending invoice auto emails to customers, any way fix this issue?

Regards

**Comment by ramth05** [comment]
@vinaykumar9999 , Auto invoice emails can be disabled `Store->Configuration->Sales->Sales Emails -> Invoice`

**Comment by vinaykumar9999** [comment]
@ramth05 
I have tried this way, no invoice emails are sent if I want to send customers manually.

Above mentioned method disable sending of Invoice Emails permanently in every payment method.

There is some code in razorpay extension which is triggering Auto send of invoices emails to customers.

**Comment by vinaykumar9999** [comment]
@ramth05 Any fix for this issue?

**Comment by ramth05** [comment]
> @ramth05 Any fix for this issue?

@vinaykumar9999 , this is default magento functionality if invoice gets generated and emails enabled it will gets send.

**Comment by yashgit891** [comment]
As the query has been resolved so closing this thread.
