### ISSUE TITLE
Magento 2.4 creating 2 orders with same payement ID

### ISSUE THREAD

**Issue by kaushikrohit54** [razorpay/razorpay-magento#283]
In some cases Magento produce 2 order ID in backend with same Trans_id, while in Razorpay dashboard it's shows only 1 order. 
Can you pls check this senerio?

**Comment by ramth05** [comment]
@kaushikrohit54 , Which version of plugin you are using currently. 
Can you please try add some more delay for webhook wait time.

**Comment by amitabesit** [comment]
Already webhook wait time is 300 sec, Still Magento 2.4 creating 2 orders with same payement ID

**Comment by ramth05** [comment]
@amitabesit, Can you please help us with some screen shot with order timing and paymentId. Let me look on it.

**Comment by kaushikrohit54** [comment]
![unnamed](https://user-images.githubusercontent.com/19974514/136771828-e34a9312-9ca8-445d-9644-b486ca331fea.png)

**Comment by ramth05** [comment]
@kaushikrohit54 , As I checked your site still using old version of the module where this issue exist. Please upgrade to the latest module 3.7.0 to fix this issue.

**Comment by ramth05** [comment]
fixed with latest version.
