### ISSUE TITLE
New Order Status: Only 'processing' order state available

### ISSUE THREAD

**Issue by HarishSTOnline** [razorpay/razorpay-magento#287]
Is there any specific reason that "New Order Status" in Configuration is bind to `Magento\Sales\Model\Config\Source\Order\Status\Processing` source model rather than `Magento\Sales\Model\Config\Source\Order\Status` ?

In `vendor/razorpay/magento/etc/adminhtml/system.xml`:71

```xml
<field id="order_status" translate="label" type="select" sortOrder="20" showInDefault="1" showInWebsite="1" showInStore="0">
    <label>New Order Status</label>
    <source_model>Magento\Sales\Model\Config\Source\Order\Status\Processing</source_model>
    <config_path>payment/razorpay/order_status</config_path>
</field>
```

At present, if someone want to change the default order state to other than `processing`, there is no option. If this has something to do with Razorpay flow, I could create a seperate `system.xml` overriding this one. 
But, I thought whether it has any specific reason.

**Comment by ramth05** [comment]
This is because we are using it for further handling of order in case webhook and crons.
