### ISSUE TITLE
Orders getting duplicated

### ISSUE THREAD

**Issue by raguventhan** [razorpay/razorpay-magento#291]
Am using the 3.7.1 version and I have configured 3 webhook events
payment.authorized
payment.captured
order.paid

Some of the orders getting duplicated. For the one payment id two orders getting created in magento backend.

**Comment by raguventhan** [comment]
Update to above issue:
1) Configured only following two events in Razorpay panel 
payment.authorized
order.paid

2) Increased the Webhook time from 300 to 500 sec. 

So far i haven't got any duplicate or missing orders.

**Comment by raguventhan** [comment]
Update to above issue:

Still the above problems not resolved.  

(Out of 305 transactions)
1) Two orders created in magento for one paymentID (For 6 transactions)
2) Orders not created in magento for captured payment (For 3 transactions)

**Comment by ramth05** [comment]
> 2\. For 3 transactions

@raguventhan , with latest release 2 order shouldn't be created for the same transaction. 
Orders not created may be some validations fails after payment. Can you please share me paymentId's and logs for the same in my email `ramprakash.singh@razorpay.com`.

**Comment by raguventhan** [comment]
Sent to your email

**Comment by ramth05** [comment]
closing it. as with new version no duplicate order placement.
