### ISSUE TITLE
Razorpay Issue : cURL error 6: Could not resolve host: api.razorpay.com

### ISSUE THREAD

**Issue by Vishal-Magento** [razorpay/razorpay-magento#306]
Hello
From few days razorpay is not working for customers... facing issue: "cURL error 6: Could not resolve host: api.razorpay.com"
before it was working fine Can you please help... Thanks In Advance.
Magento v: 2.4.2.

**Comment by yashgit891** [comment]
Please check with latest version, this should not occur.
