### ISSUE TITLE
Unable to process the order 

### ISSUE THREAD

**Issue by ketanmittal** [razorpay/razorpay-magento#31]
Unable to process the order after Compilation. Our environment details are as follows:

Magento version - 1.9.2.4
HTTP server - nGinx

**Comment by mayankamencherla** [comment]
Hi, Can you try getting our latest release and try seeing if the issue persists?

**Comment by mayankamencherla** [comment]
@ketanmittal Hi, can you please update us here?

**Comment by mayankamencherla** [comment]
No response - closing
