### ISSUE TITLE
Magento 2.3.1 Undefined index: label

### ISSUE THREAD

**Issue by vishalpatel19862** [razorpay/razorpay-magento#313]
I am using Magento 2.3.1
I have installed the Razor pay module below 2.3.3.
If I click on the view order on the admin panel, we are getting the below error.

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: label in /home2/dev1/www/vendor/magento/module-backend/Block/Widget/Grid/Column/Filter/Select.php on line 75

**Comment by yashgit891** [comment]
Please use the latest versions, this issue will not occur.
