### ISSUE TITLE
Magento 2.3.7 p-2 : Customer does not have an active cart

### ISSUE THREAD

**Issue by aniruddharay** [razorpay/razorpay-magento#322]
Razorpay redirect to `checkout/cart` instead of `checkout/onepage/success`, after payment processing is complete.

During payment processing, shows the error  _**Customer does not have an active cart**_, and goes to blank cart page. 

![Screenshot 2022-01-28 at 12 59 27 PM](https://user-images.githubusercontent.com/69155933/152291333-0792b1e9-7ccc-4c6b-ac04-affca8d29c5c.png)

After some digging, found out that when order is placed through webhook, this issue occurs. Otherwise , it goes to success page. 

![image](https://user-images.githubusercontent.com/69155933/152291496-1ea70c84-1025-4b1b-aad6-2733266fcf42.png)

Magento version was upgraded from 2.3.4 to 2.3.7 p-2 recently, and this issue surfaced after that. 

Razorpay is at it's latest version
![screenshot-nimbus-capture-2022 02 03-11_52_30](https://user-images.githubusercontent.com/69155933/152291899-55181875-66ca-42f3-8d33-d7e4ffeef121.png)

**Comment by yashgit891** [comment]
Hello, please check out latest version where flow has been changed.
