### ISSUE TITLE
want card details to be entered on our website intead of pop up or iframe

### ISSUE THREAD

**Issue by ia-gaurav** [razorpay/razorpay-magento#334]
want card details to be entered on our website intead of pop up or iframe

**Comment by anandmaldikar1** [comment]
For Plugins, we only have standard checkout integration where you will get a popup to enter the card details or to select the Payment method.
For the rest of the server integrations, you can follow below integration document.

https://razorpay.com/docs/payments/payment-gateway/web-integration/custom/

**Comment by yashgit891** [comment]
Closing this ticket as query has been addressed.
