### ISSUE TITLE
error Undefined class constant 'DISABLE_UPGRADE_NOTICE'

### ISSUE THREAD

**Issue by ia-gaurav** [razorpay/razorpay-magento#340]
Magento : 2.4
Plugin version - [beta-3.3.4](https://github.com/razorpay/razorpay-magento/releases/tag/beta-3.3.4)

Error - I see below error in admin panel Undefined class constant 'DISABLE_UPGRADE_NOTICE'

Also when we can expect final version

**Comment by yashgit891** [comment]
This issue has been resolved and final version has also been released.
