### ISSUE TITLE
When One Transaction Done merchant_order_id is missing in the Notes

### ISSUE THREAD

**Issue by binumathew** [razorpay/razorpay-magento#347]
As a Magento customer logged in and selected one product and after payment successful when I check the Transaction in the Notes, I show

merchant_order_id
--
merchant_quote_id
107

Any idea why my  merchant_order_id is missing?
Magento ver. 2.3.5-p2
Razor Pay Magento Plugin  Ver 2.9.4

**Comment by yashgit891** [comment]
Hello, please check latest versions these issue should not occur.
