### ISSUE TITLE
Magento 2.4.4 Compatibility

### ISSUE THREAD

**Issue by karthikmallireddy** [razorpay/razorpay-magento#362]
Unable to Install the Razor Pay Extension using Composer for Magento 2.4.4.

**Comment by avi-commerce** [comment]
I have faced the same issue when we install the Razor Pay extension in Magento 2.4.4

**Comment by ravikumarkarri** [comment]
I have faced similar issue for my new magento 2.4.4 application. It is issue with PHP 8.1 version. I hope the team will fix the compatible issues, Waiting for solution.

**Comment by rauljitechnologies** [comment]
![image](https://user-images.githubusercontent.com/106725861/172428865-c89e31dd-8053-4f23-ae11-7f849032d5b4.png)

i have faced similar issue for new magento 2.4.4 version.

**Comment by yashgit891** [comment]
This issue has been resolved so closing it here.
