### ISSUE TITLE
Issue with RazorPay Newest Version 4.0.1 in Magento 2.4.5

### ISSUE THREAD

**Issue by vinaykumar9999** [razorpay/razorpay-magento#396]
Hi

Getting this error while saving the configuration in Razorpay Payment Method

Error: Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource in /home/test/xyz/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50

Magento 2.4.5 with PHP 8.1 > Latest RazorPay Version 4.0.1

How to fix this issue?

**Comment by enishant** [comment]
Please execute following commands from Magento root directory.
```
php bin/magento setup:di:compile
php bin/magento setup:upgrade
php bin/magento cache:flush
```

Execute following commands, if maximum memory required while execution.
```
php -dmemory_limit=-1 bin/magento setup:di:compile
php -dmemory_limit=-1 bin/magento setup:upgrade
php -dmemory_limit=-1 bin/magento cache:flush
```

Then at the Magento admin dashboard, open Razorpay payment method settings and click on the `Save Config` button. Please comment to know if you still face any issues after applying above actions.

**Comment by vinaykumar9999** [comment]
I have successfully run all the above mentioned commands.

Screenshot : https://prnt.sc/u8669uA23nEn

Screenshot : https://prnt.sc/6WzBxVvaZoQx

Still Facing the same error while clicking on save config button.

May be the issue is related to constructor.

Ref Link : https://community.magento.com/t5/Magento-2-x-Technical-Issues/Magento-2-Error-Cannot-instantiate-abstract-class-Magento/m-p/501448

**Comment by vinaykumar9999** [comment]
Hi

Version 4.0.0 is not throwing any error. There is some issue in V4.0.1(Please Check it)

Facing some issues with V4.0.0

1. On Checkout Page>When customer click on Show QR Code >And close RazorPay window. Extension places order automatically. How to stop this behavior.

2. Order Status must come as Pending in Backend, But it is coming Processing after the above process (Mentioned in Step 1).

How to fix these issues?

Regards

**Comment by gopal2k6** [comment]
We are facing same issue in Fresh Magento install in 2.4.5-p1. Please review code and update this issue.

**Comment by sanganinamrata** [comment]
I'm also facing the same issue since today post module upgrade to 4.0.1

**Comment by gopal2k6** [comment]
Hi Team,

Is that any update regarding this issue?? We need to go live with New Version. Please update soon as possible.


Regards
-G

**Comment by jatinderkumar-india** [comment]
Hi 

Issue still exists with RazorPay Newest Version 4.0.1. Please provide the fix on this. 

Thanks

**Comment by enishant** [comment]
This issue has been fixed with latest commits, we will release this fix with our upcoming version. If you are expecting fixed changes before release you can use following instructions:

### Install through composer
`composer require razorpay/magento:dev-master-2.x`

### Install through code.zip
Download [code.zip](https://github.com/razorpay/razorpay-magento/files/10075095/code.zip) provided here.

Use above code via composer OR code.zip and refer release [document](https://github.com/razorpay/razorpay-magento/releases/tag/4.0.1) for installation instructions.

**Comment by vinaykumar9999** [comment]
Hi

That Previous Error is fixed in dev-master

But Above Mentioned Behavior with QR Code is present.

> On Checkout Page>When customer click on Show QR Code >And close RazorPay window. Extension places order automatically. How to stop this behavior?

This issue is with UPI only. All others methods are not placing order on Failure of payment.

Screenshot : https://prnt.sc/_SkDHQDUp-A5

Regards

**Comment by enishant** [comment]
> Hi
> 
> That Previous Error is fixed in dev-master
> 
> But Above Mentioned Behavior with QR Code is present.
> 
> > On Checkout Page>When customer click on Show QR Code >And close RazorPay window. Extension places order automatically. How to stop this behavior?
> 
> This issue is with UPI only. All others methods are not placing order on Failure of payment.
> 
> Screenshot : https://prnt.sc/_SkDHQDUp-A5
> 
> Regards

@vinaykumar9999 Regarding this checkout page issue, please raise a [support ticket](https://razorpay.com/support/#request) along with your MID and mode that you are using while processing transaction.

**Comment by vinaykumar9999** [comment]
@enishant Is there any update on the Custom Status when order is placed?

Regards

**Comment by enishant** [comment]
> @enishant Is there any update on the Custom Status when order is placed?
> 
> Regards

@vinaykumar9999 For this functionality QA is still in progress, feature will be available with an upcoming version.

**Comment by enishant** [comment]
Closing this issue with fix -> https://github.com/razorpay/razorpay-magento/issues/396#issuecomment-1324931809
