### ISSUE TITLE
OneStep Checkout with Razorpay is navigating to Standard Checkout

### ISSUE THREAD

**Issue by karthikmallireddy** [razorpay/razorpay-magento#405]
Hi,

If a user cancels the payment from the Mageplaza Onestep Checkout, It's redirecting to the standard payment checkout page. Can you provide some solution?

Magento Version:2.4.5

Razor Pay Version:4.0.2

**Comment by enishant** [comment]
Please find **[code.zip](https://github.com/razorpay/razorpay-magento/files/10978862/code.zip)** file for updated changes, if you are using composer updated code can be setup using following command.

```
composer require razorpay/magento:dev-onepage_checkout_redirect_issue
```
