### ISSUE TITLE
Showing error on compilation

### ISSUE THREAD

**Issue by kaushikrohit54** [razorpay/razorpay-magento#406]
PHP Warning:  Uncaught Exception: Warning: require_once(/var/www/html/vendor/razorpay/magento/Model/System/Message/../../../../Razorpay/Razorpay.php): failed to open stream: No such file or directory in /var/www/html/vendor/razorpay/magento/Model/System/Message/UpgradeMessageNotification.php on line 12 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/html/vendor/razorpay/magento/Model/System/Message/UpgradeMessageNotification.php(12): Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/html/vendor/razorpay/magento/Model/System/Message/UpgradeMessageNotification.php(12): require_once()
#2 /var/www/html/vendor/composer/ClassLoader.php(444): include('/var/www/html/v...')
#3 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#5 [internal function]: spl_autoload_call()
#6 /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#7 /var/www/ in /var/www/html/vendor/magento/framework/App/ErrorHandler.php on line 61
PHP Fatal error:  main(): Failed opening required '/var/www/html/vendor/razorpay/magento/Model/System/Message/../../../../Razorpay/Razorpay.php' (include_path='/var/www/html/generated/code:/var/www/html/generated/code:/var/www/html/vendor/magento/zendframework1/library:.:/usr/share/php') in /var/www/html/vendor/razorpay/magento/Model/System/Message/UpgradeMessageNotification.php on line 12

**Comment by enishant** [comment]
@kaushikrohit54 According to above error message Razorpay module installed using `composer` and Razorpay SDK library is not exists at your `vendor` directory which is required. You can install it manually by using following command and compile code again.
```
composer require razorpay/razorpay:2.*
```

Please follow instructions provided at release document for installation
https://github.com/razorpay/razorpay-magento/releases/tag/4.0.2
