### ISSUE TITLE
Cart is cleared after payment failed when creating order with Graph QL

### ISSUE THREAD

**Issue by Harryalways317** [razorpay/razorpay-magento#427]
Repro Steps:
1. create an order with GraphQL. After successfully placing the order, we are creating the razorpay order using the order_id generated as per https://github.com/razorpay/razorpay-magento#working-with-graphql.
2. When payment fails, the cart gets cleared as order is created. When we call the resetCart API 

what are the steps to achieve the reset cart functionality to reset the cart to previous quote when we are using the graphQL API?

**Comment by yashgit891** [comment]
@Harryalways317 latest release has reset cart functionality for GraphQL please check that out.
