### ISSUE TITLE
Error when try to upgrade extension version 4.0.4 in Magento version 2.4.2

### ISSUE THREAD

**Issue by dev-amitsaini** [razorpay/razorpay-magento#435]
Hello,
I am trying to upgrade the extension version to the latest (4.0.4), but after the composer update extension when I tried to run the "setup:upgrade" command, the below error is showing:
PHP Warning:  Uncaught Exception: Warning: require_once(/vendor/razorpay/magento/Model/../../Razorpay/Razorpay.php): failed to open stream: No such file or directory in /vendor/razorpay/magento/Model/TrackPluginInstrumentation.php on line 17

And Line 17 code:
![image](https://github.com/razorpay/razorpay-magento/assets/40263639/b02a9621-7064-4ba3-ae67-ebb55510762d)
Also, what is the "WpOrg\Requests\Autoload" dependency? Because in the previous version (3.7.5), this dependency was not showing. Also, after the composer update extension, there is no "WpOrg\Requests" dependency showing in the "vendor" directory.

**Comment by himanshuv4** [comment]
I am getting same error version 4.1.2 in magento 2.3

**Comment by yashgit891** [comment]
Hello,
Can you folks try with the latest release and if issue still persists please share the error.
