### ISSUE TITLE
Not compatible with PHP8.2 and Magento2.4.6-p1

### ISSUE THREAD

**Issue by syedsaleem086** [razorpay/razorpay-magento#449]
Hi,

We installed the default magento2.4.6-p1 with PHP8.2 the checkout page goes blank

We installed latest Razorpay using composer

Kind Regards,
Syed

**Comment by VishalAgarwal** [comment]
Hi requesting to resolve this on priority.

**Comment by sachingulwane1** [comment]
File:

Model/TrackPluginInstrumentation.php

updating funtion on line 35  -   TrackPluginInstrumentation

as bellow, has fixed it for me. on Magento 2.4.6  PHP 8.2

Updated function Code:

class TrackPluginInstrumentation
{
    const MODULE_NAME = 'Razorpay_Magento';

    protected $api;

    protected $mode;

    protected $moduleList;
    
    protected \Razorpay\Magento\Model\Config $config; // Add explicit property declaration
    protected \Psr\Log\LoggerInterface $logger; // Add explicit property declaration

    public function __construct(
        \Razorpay\Magento\Model\Config $config, // Update parameter type hint
        ModuleListInterface $moduleList,
        \Psr\Log\LoggerInterface $logger // Update parameter type hint
    )
    {
        $this->config       = $config;
        $this->api          = $this->setAndGetRzpApiInstance();
        $this->moduleList   = $moduleList;
        $this->logger       = $logger;
    }


Update: this only fixes installation error, but there are some more errors on checkout page.

**Comment by nicedhanraj** [comment]
I am having the same issue. This issues means that we cannot have Razorpay on Magento 2.4.6.

**Comment by gijoe707** [comment]
I get this error when trying to initialize payment on Magento 2.4.6.p4

main.CRITICAL: Exception: Deprecated Functionality: Creation of dynamic property Cashfree\Cfcheckout\Observer\AfterPlaceOrderObserver::$checkoutSession is deprecated in /bitnami/magento/app/code/Cashfree/Cfcheckout/Observer/AfterPlaceOrderObserver.php on line 48 in /bitnami/magento/vendor/magento/framework/App/ErrorHandler.php:62

**Comment by ramth05** [comment]
@gijoe707 , this is not related to Razorpay.

**Comment by ramth05** [comment]
We have already release latest plugin with php8.2 support.
