### ISSUE TITLE
Cart order amount doesn't match with amount paid

### ISSUE THREAD

**Issue by parveenkhan22** [razorpay/razorpay-magento#457]
Hi,
My order enters the abandoned cart after I successfully pay for it with Razorpay.
I'm getting an error in the exception log; see the screenshot below
![image] (https://github.com/razorpay/razorpay-magento/assets/57412408/da38a641-4ae9-48ab-898d-5c60fc561ef4).
I searched the quote_id and found in the razorpay_sales_order table with payment info with a null order_id, which is why I was unable to view the order in the admin.
I am using razorpay 3.7.5 in magento 2.4.3-p1
Please have a look at this.
Thanks!

**Comment by yashgit891** [comment]
@parveenkhan22 please upgrade to the latest version of the plugin to avoid such issues. In it we have changed to new flow for magento order placement before payment.

**Comment by raguventhan** [comment]
Hi @yashgit891

if an order placed before payment it will create many problems in default cart flow, explained in detail here [https://github.com/razorpay/razorpay-magento/issues/431#issuecomment-1914028922](https://github.com/razorpay/razorpay-magento/issues/431#issuecomment-1914028922).

Instead you can have an option to allow if cart order amount not matched the amount paid. We are using custom coupon, giftcard and store credit options. When combining this with Razorpay it will throw this error.

So, placing order before payment is not a correct solution for this issue.

**Comment by yashgit891** [comment]
Hello @raguventhan 
Whatever is the final amount to be paid for the order only that would be captured by Razorpay. I suggest testing out these scenarios on a staging site with the latest plugin version and which ever is not working please describe the issue in detail.

**Comment by yashgit891** [comment]
As there is no response so closing this thread.
