### ISSUE TITLE
Column not found: 1054 Unknown column 'main_table.rzp_webhook_notified_at

### ISSUE THREAD

**Issue by ashok1421** [razorpay/razorpay-magento#487]
Hello,
I am using the Razor pay module version 4.1.4
I found the error in my exception.log file.
`main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.rzp_webhook_notified_at' in 'field list', query was: SELECT `main_table`.`entity_id`, `main_table`.`rzp_webhook_notified_at` FROM `sales_order` AS `main_table` WHERE (increment_id='2425000000005') {"report_id":"c966397c15ac157f1dbea0d8da72812c815f1ac101154b95b84ed64d41f47344","exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.rzp_webhook_notified_at' in 'field list', query was: SELECT `main_table`.`entity_id`, `main_table`.`rzp_webhook_notified_at` FROM `sales_order` AS `main_table` WHERE (increment_id='2425000000005') at /usr/local/lsws/svaraa/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.rzp_webhook_notified_at' in 'field list' at /usr/local/lsws/svaraa/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []`
Please check this issue.
Here used rzp_webhook_notified_at in  protected function getOrderWebhookData($orderId) : array
<img width="940" alt="Screenshot 2024-05-13 at 5 32 14 PM" src="https://github.com/razorpay/razorpay-magento/assets/75234796/773eb9c5-a6e6-455d-94f8-c201b977f09f">

Please check the attached file.
Thank You.

**Comment by sanganinamrata** [comment]
Hello @razorpay-sanjib & team,

I'm also facing the same issue after the latest upgrade. My 4 live clients were already using this module & after the upgrade, their webhooks got broken due to this error.

Any urgent help would be appreciated.

Thanks in advance.

**Comment by yashgit891** [comment]
@ashok1421 can you the schema of razorpay_sales_order table and check if these columns are present there?

**Comment by ashok1421** [comment]
Yes In the razorpay_sales_order table columns  rzp_webhook_notified_at are present.

**Comment by yashgit891** [comment]
@ashok1421 okay and what is the `prx` in the query? Is this some other module as it does not look Razorpay related.

**Comment by ashok1421** [comment]
@yashgit891 "prx" is only table prefix of my local project.
The issue is rzp_webhook_notified_at columns filter in sales_order table so this error occrud

**Comment by yashgit891** [comment]
@ashok1421 identified the bug here, will provide a solution for the same in the next release.Sorry for the inconvenience.

**Comment by ashok1421** [comment]
@yashgit891 Thank you

**Comment by ashok1421** [comment]
Hello @yashgit891 ,
Here I solved the issue So please check the solutions.
I Attached the patch here.
[webhook.patch](https://github.com/razorpay/razorpay-magento/files/15319670/webhook.patch)

**Comment by sanganinamrata** [comment]
Hello @ashok1421,

Thank you! Your provided patch worked for me.

@yashgit891 Will you please check the patch given by @ashok1421 & test it, if all is well, let's merge it on the current repo & make it an official release.

Thanks.

**Comment by ashok1421** [comment]
Hello @yashgit891 , 
can you please tell me Any update on this issue ?

**Comment by yashgit891** [comment]
@ashok1421 we have implemented a fix but release might take time. In the meantime you can use this [PR](https://github.com/razorpay/razorpay-magento/pull/489) as a fix .

**Comment by yashgit891** [comment]
This bug has been resolved in latest release.
