### ISSUE TITLE
Column not found: 1054 Unknown column 'rzp_update_order_cron_status' 

### ISSUE THREAD

**Issue by ashok1421** [razorpay/razorpay-magento#501]
Hello @yashgit891 ,
I am using the Razor pay module version 4.1.6. 
I show error in a log file.
`Cron Job razorpay_update_order_to_processing has an error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rzp_update_order_cron_status' in 'where clause', query was: SELECT `main_table`.*, `extension_attribute_pickup_location_code`.`pickup_location_code` AS `extension_attribute_pickup_location_code_pickup_location_code`, `extension_attribute_notification_sent`.`notification_sent` AS `extension_attribute_notification_sent_notification_sent`, `extension_attribute_send_notification`.`send_notification` AS `extension_attribute_send_notification_send_notification` FROM `sales_order` AS `main_table`
 LEFT JOIN `inventory_pickup_location_order` AS `extension_attribute_pickup_location_code` ON main_table.entity_id = extension_attribute_pickup_location_code.order_id
 LEFT JOIN `inventory_order_notification` AS `extension_attribute_notification_sent` ON main_table.entity_id = extension_attribute_notification_sent.order_id
 LEFT JOIN `inventory_order_notification` AS `extension_attribute_send_notification` ON main_table.entity_id = extension_attribute_send_notification.order_id WHERE ((`rzp_update_order_cron_status` < 5)) AND ((`rzp_webhook_notified_at` != '')) AND ((`rzp_webhook_notified_at` < 1724227249)) AND ((`status` = 'pending')) ORDER BY main_table.entity_id DESC
. Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":341311488,"emalloc_start":320998264} [] []
[2024-08-21 08:05:49] main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rzp_update_order_cron_status' in 'where clause', query was: SELECT `main_table`.*, `extension_attribute_pickup_location_code`.`pickup_location_code` AS `extension_attribute_pickup_location_code_pickup_location_code`, `extension_attribute_notification_sent`.`notification_sent` AS `extension_attribute_notification_sent_notification_sent`, `extension_attribute_send_notification`.`send_notification` AS `extension_attribute_send_notification_send_notification` FROM `sales_order` AS `main_table`
 LEFT JOIN `inventory_pickup_location_order` AS `extension_attribute_pickup_location_code` ON main_table.entity_id = extension_attribute_pickup_location_code.order_id
 LEFT JOIN `inventory_order_notification` AS `extension_attribute_notification_sent` ON main_table.entity_id = extension_attribute_notification_sent.order_id
 LEFT JOIN `inventory_order_notification` AS `extension_attribute_send_notification` ON main_table.entity_id = extension_attribute_send_notification.order_id WHERE ((`rzp_update_order_cron_status` < 5)) AND ((`rzp_webhook_notified_at` != '')) AND ((`rzp_webhook_notified_at` < 1724227249)) AND ((`status` = 'pending')) ORDER BY main_table.entity_id DESC
 {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rzp_update_order_cron_status' in 'where clause', query was: SELECT `main_table`.*, `extension_attribute_pickup_location_code`.`pickup_location_code` AS `extension_attribute_pickup_location_code_pickup_location_code`, `extension_attribute_notification_sent`.`notification_sent` AS `extension_attribute_notification_sent_notification_sent`, `extension_attribute_send_notification`.`send_notification` AS `extension_attribute_send_notification_send_notification` FROM `sales_order` AS `main_table`
 LEFT JOIN `inventory_pickup_location_order` AS `extension_attribute_pickup_location_code` ON main_table.entity_id = extension_attribute_pickup_location_code.order_id
 LEFT JOIN `inventory_order_notification` AS `extension_attribute_notification_sent` ON main_table.entity_id = extension_attribute_notification_sent.order_id
 LEFT JOIN `inventory_order_notification` AS `extension_attribute_send_notification` ON main_table.entity_id = extension_attribute_send_notification.order_id WHERE ((`rzp_update_order_cron_status` < 5)) AND ((`rzp_webhook_notified_at` != '')) AND ((`rzp_webhook_notified_at` < 1724227249)) AND ((`status` = 'pending')) ORDER BY main_table.entity_id DESC
 at vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rzp_update_order_cron_status' in 'where clause' at vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []
[2024-08-21 08:05:49] main.INFO: Cron Job razorpay_update_order_to_processing_v2 is run [] []`

Please check this error

Thank you

**Comment by yashgit891** [comment]
Hello @ashok1421 please disable the UpdateOrderToProcessing Cron from the Razorpay plugin settings as it is no longer needed and it is available for users who are upgrading from a fairly older version of the plugin.
