### ISSUE TITLE
Got an error at checkout point 

### ISSUE THREAD

**Issue by sup077** [razorpay/razorpay-magento#53]
Fatal error: Uncaught Error: Class 'Razorpay\Api\Api' not found in /home/jkbinfot/public_html/jindeal.com/app/code/Razorpay/Magento/Controller/BaseController.php:59 Stack trace: #0 /home/jkbinfot/public_html/jindeal.com/app/code/Razorpay/Magento/Controller/Payment/Order.php(34): Razorpay\Magento\Controller\BaseController->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\Config)) #1 /home/jkbinfot/public_html/jindeal.com/var/generation/Razorpay/Magento/Controller/Payment/Order/Interceptor.php(14): Razorpay\Magento\Controller\Payment\Order->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Customer\Model\Session\Interceptor), Object(Magento\Checkout\Model\Session\Interceptor), Object(Razorpay\Magento\Model\CheckoutFactory), Object(Razorpay\Magento\Model\Config), Object(Magento\Catalog\Model\Session\Interceptor)) #2 /home/jkbinfot/public_html/jindeal.com/vendor/ in /home/jkbinfot/public_html/jindeal.com/app/code/Razorpay/Magento/Controller/BaseController.php on line 59

**Comment by mayankamencherla** [comment]
Hi, @sup077 

Could you please share with us the way in which you've installed the magento 2.x plugin?

**Comment by mayankamencherla** [comment]
The correct way to install the plugin is: 

https://docs.razorpay.com/v1/page/magento

**Comment by abhisekhranjan** [comment]
Hi I am getting the issues.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed

**Comment by abhisekhranjan** [comment]
Another Issue is when i am installing manually .
Cart Page & Checkout Page Stop Working.
