### ISSUE TITLE
[Magento-2.x] Redirect plugin

### ISSUE THREAD

**Issue by ccrims0n** [razorpay/razorpay-magento#60]

**Comment by mayankamencherla** [comment]
We will be creating a new redirection based plugin instead.

**Comment by mayankamencherla** [comment]
I have working code for this. Tested. Need to confirm with @ccrims0n before releasing / testing.

**Comment by mayankamencherla** [comment]
Tested and done cc @ccrims0n 
https://github.com/razorpay/razorpay-magento/tree/master-2.x-redirect

**Comment by mayankamencherla** [comment]
Sent to the customer after testing.
