### ISSUE TITLE
Unable to make a payment when opted for Multi-shipping address

### ISSUE THREAD

**Issue by Mayur-Wadpalliwar** [razorpay/razorpay-magento#61]
**Steps to reproduce:**

- go to Store/Configuration/Sales/MultiShipping Settings/ Allow Shipping to Multiple Addresses = Yes
- Go to Magento site and select a product.
- Go to cart and select "Check Out with Multiple Addresses" and then place order 
- As soon we click on "place order" and error will be thrown as **"Warning: hash_equals(): Expected user_string to be a string, null given in ../vendor/razorpay/magento/Model/PaymentMethod.php on line 272"**
- Also, after placing an order, the checkout is not opening and it is directly verifying the signature.
- Initial analysis is that we are getting the value of **actualString** as **NULL**

![in_case_of_multishipping_1st_step](https://user-images.githubusercontent.com/28298004/27957394-f115aec2-633b-11e7-987e-e90bed114c00.png)
![in_case_of_multishipping](https://user-images.githubusercontent.com/28298004/27957399-f6ba7e02-633b-11e7-8fc2-3fe56c6c4ea6.png)

**Comment by Mayur-Wadpalliwar** [comment]
https://razorpay.zendesk.com/agent/tickets/77832

**Comment by ramth05** [comment]
currently Multi-shipping not supported.
