### ISSUE TITLE
Fix User Agent

### ISSUE THREAD

**Issue by ace03uec** [razorpay/razorpay-magento#8]
- User Agent string does not include razorpay-magento version.
- User Agent string should not be formatted with ' '.

**Comment by captn3m0** [comment]
This is for which version of the plugin? 1 or 2? I'm pretty sure @73sl4 wrote code for this for Magento 2.

**Comment by ace03uec** [comment]
This was for Magento 1.

**Comment by mayankamencherla** [comment]
https://github.com/razorpay/razorpay-magento/pull/66
