### ISSUE TITLE
To display Razorpay logo in payment options in Magento

### ISSUE THREAD

**Issue by Mayur-Wadpalliwar** [razorpay/razorpay-magento#82]
![screen-ref](https://user-images.githubusercontent.com/28298004/29870664-5a1c641c-8da6-11e7-883a-2d5ab8a9c80c.jpg)

ref: 91012

**Comment by Mayur-Wadpalliwar** [comment]
<img width="1196" alt="screen shot 2017-08-30 at 6 29 29 pm" src="https://user-images.githubusercontent.com/28298004/29873527-3812be24-8db1-11e7-9a0d-ca26734f6468.png">

**Comment by mayankamencherla** [comment]
http://www.waimichael.idv.hk/how-to-add-logo-or-additional-information-to-custom-payment-method-in-magento/

**Comment by mayankamencherla** [comment]
Able to do this locally. @ccrims0n Let us discuss this once and we can release it.
<img width="1280" alt="screen shot 2017-12-03 at 1 36 47 am" src="https://user-images.githubusercontent.com/18058797/33519323-8e88bba6-d7ca-11e7-84c2-99f2fd09c396.png">

**Comment by zersys** [comment]
Hi Guys, has this been released, I would like to  do this on my site as well.

**Comment by mayankamencherla** [comment]
@zersys Not yet. We will release it soon. Thanks for your patience.

**Comment by tosswithim** [comment]
Hello, 

I am using magento 1.9.3.6 and facing same issues, @mayankamencherla as an biggner unable to fix the issue, which is provided by you in previous [link](http://www.waimichael.idv.hk/how-to-add-logo-or-additional-information-to-custom-payment-method-in-magento/)

Please do the needful 

Himanshu

**Comment by ramth05** [comment]
Already supported.
